import { useEffect,useState } from 'react';
import { NavLink,Outlet,useLocation } from 'react-router-dom';
import { useAuth } from '../auth/AuthContext';
import { useI18n,type TranslationKey } from '../i18n/I18nContext';
import { ThemeToggle } from './ThemeToggle';
import { LanguageToggle } from './LanguageToggle';
type Item={to:string;key:TranslationKey;analystOnly?:boolean};type Group={key:TranslationKey;accent:string;adminOnly?:boolean;links:Item[]};
const groups:Group[]=[{key:'operations',accent:'dashboard',links:[{to:'/',key:'dashboard'},{to:'/processing-center',key:'processingCenter'}]},{key:'external',accent:'external',links:[{to:'/external-sources',key:'sources'},{to:'/manual',key:'manual',analystOnly:true},{to:'/dark-web',key:'darkWeb'},{to:'/jobs',key:'jobs'},{to:'/reviews',key:'reviews'},{to:'/exports',key:'exports'}]},{key:'internal',accent:'internal',links:[{to:'/internal-sources',key:'overview'},{to:'/internal-sources/dionaea',key:'sources'},{to:'/internal-sources/host-auth',key:'hostAuth'},{to:'/internal-sources/web-access',key:'webAccess'}]},{key:'intelligence',accent:'analysis',links:[{to:'/intelligence',key:'overview'},{to:'/intelligence/events',key:'events'},{to:'/intelligence/indicators',key:'indicators'},{to:'/intelligence/attack',key:'attack'},{to:'/intelligence/correlations',key:'correlations'},{to:'/intelligence/outliers',key:'outliers'},{to:'/analysis',key:'analysisRuns'},{to:'/misp',key:'misp'}]},{key:'administration',accent:'admin',adminOnly:true,links:[{to:'/admin',key:'admin'}]}];
function Icon(){return <svg className="nav-icon" viewBox="0 0 24 24" aria-hidden="true" fill="none" stroke="currentColor"><circle cx="12" cy="12" r="8"/><path d="M8 12h8M12 8v8"/></svg>}
export function Layout(){const {user,logout,can}=useAuth(),{t}=useI18n(),{pathname}=useLocation();const [menuOpen,setMenuOpen]=useState(false),[collapsed,setCollapsed]=useState(false);useEffect(()=>setMenuOpen(false),[pathname]);useEffect(()=>{if(!menuOpen)return;const close=(e:KeyboardEvent)=>e.key==='Escape'&&setMenuOpen(false);document.addEventListener('keydown',close);return()=>document.removeEventListener('keydown',close)},[menuOpen]);const all=groups.flatMap(g=>g.links.map(l=>[l.to,{title:t(l.key),group:t(g.key)}] as const));const context=Object.fromEntries(all)[pathname]||(pathname.startsWith('/intelligence/events/')?{title:t('events'),group:t('intelligence')}:{title:t('workspace'),group:t('platform')});const role=user?.role==='admin'?t('administrator'):user?.role==='analyst'?t('analyst'):t('viewer');return <div className={`app-shell ${collapsed?'sidebar-collapsed':''}`}><button className={`sidebar-backdrop ${menuOpen?'visible':''}`} aria-label={t('closeNav')} onClick={()=>setMenuOpen(false)} tabIndex={menuOpen?0:-1}/><aside id="primary-navigation" className={`sidebar ${menuOpen?'open':''}`} aria-label={t('primaryNav')}><div className="brand"><span className="brand-mark">CTI</span><div className="collapsible-copy"><strong>{t('brand')}</strong><small>{t('brandSub')}</small></div></div><button className="collapse-toggle" onClick={()=>setCollapsed(v=>!v)} aria-label={collapsed?t('expandNav'):t('collapseNav')} aria-expanded={!collapsed}>⇔</button><nav aria-label={t('primaryNav')}>{groups.filter(g=>!g.adminOnly||user?.role==='admin').map(g=><section className={`nav-group nav-${g.accent}`} key={g.key} aria-label={t(g.key)}><h2>{t(g.key)}</h2>{g.links.filter(l=>!l.analystOnly||can('analyst')).map(l=><NavLink key={l.to} to={l.to} end={l.to==='/'||l.to==='/intelligence/events'} className={({isActive})=>isActive?'nav-link active':'nav-link'} title={t(l.key)}><Icon/><span>{t(l.key)}</span></NavLink>)}</section>)}</nav><div className="sidebar-foot"><span className="online-dot"/><span className="collapsible-copy"><strong>{t('secureSession')}</strong><small>{t('secureConnection')}</small></span></div></aside><main className="main-content"><header className="topbar"><div className="topbar-context"><button className="menu-toggle" aria-label={t('openNav')} aria-controls="primary-navigation" aria-expanded={menuOpen} onClick={()=>setMenuOpen(true)}><span/><span/><span/></button><div><span className="breadcrumb">{context.group} / {t('platform')}</span><h1>{context.title}</h1></div></div><div className="user-menu"><span className="session-status"><span className="online-dot"/>{t('sessionActive')}</span><LanguageToggle/><ThemeToggle/><div className="avatar">{user?.username.slice(0,1).toUpperCase()}</div><div className="user-copy"><strong>{user?.username}</strong><small>{role}</small></div><button className="button button-quiet logout-button" onClick={logout}>{t('logout')}</button></div></header><Outlet/></main></div>}
