import {useEffect,useRef,useState} from 'react';
import {useQuery} from '@tanstack/react-query';
import {api} from '../api/client';
import {EmptyState,ErrorState,LoadingState} from '../components/States';
import {useAuth} from '../auth/AuthContext';
import {useI18n} from '../i18n/I18nContext';
import './AcceptedRecords.css';
import {externalQueryKeys} from '../api/externalQueryKeys';

export function AcceptedRecords(){
  const {t,number,dateTime}=useI18n(),{can}=useAuth();
  const [offset,setOffset]=useState(0),[search,setSearch]=useState(''),[selected,setSelected]=useState('');
  const dialog=useRef<HTMLDivElement>(null),opener=useRef<HTMLButtonElement|null>(null);
  const limit=20;
  const page=useQuery({queryKey:externalQueryKeys.acceptedRecords(offset,search),queryFn:({signal})=>api.acceptedRecords(limit,offset,{search:search.trim().length>=2?search.trim():undefined},signal)});
  const detail=useQuery({queryKey:externalQueryKeys.acceptedRecord(selected),queryFn:({signal})=>api.acceptedRecord(selected,signal),enabled:Boolean(selected)});
  function open(id:string,button:HTMLButtonElement){opener.current=button;setSelected(id)}
  function close(){setSelected('');window.setTimeout(()=>opener.current?.focus(),0)}
  useEffect(()=>{if(!selected)return;const previous=document.body.style.overflow;document.body.style.overflow='hidden';const node=dialog.current;node?.querySelector<HTMLElement>('button,[href],input,select,textarea,[tabindex]:not([tabindex="-1"])')?.focus();const key=(event:KeyboardEvent)=>{if(event.key==='Escape'){event.preventDefault();close();return}if(event.key!=='Tab'||!node)return;const focusable=[...node.querySelectorAll<HTMLElement>('button,[href],input,select,textarea,[tabindex]:not([tabindex="-1"])')].filter(value=>!value.hasAttribute('disabled'));if(!focusable.length)return;const first=focusable[0],last=focusable[focusable.length-1];if(event.shiftKey&&document.activeElement===first){event.preventDefault();last.focus()}else if(!event.shiftKey&&document.activeElement===last){event.preventDefault();first.focus()}};document.addEventListener('keydown',key);return()=>{document.removeEventListener('keydown',key);document.body.style.overflow=previous}},[selected]);
  return <section className="page-section"><div className="section-heading"><div><span className="eyebrow">{t('intelligence')}</span><h2>{t('acceptedRecords')}</h2><p>{t('acceptedRecordsDescription')}</p></div></div>
    <div className="filters"><label className="search-wrap"><span className="sr-only">{t('search')}</span><input value={search} onChange={event=>{setSearch(event.target.value);setOffset(0)}} placeholder={t('searchAcceptedRecords')}/></label></div>
    {page.isLoading&&<LoadingState/>}{page.isError&&page.data&&<div className="state-panel" role="status"><strong>{t('staleDataWarning')}</strong><button className="button button-secondary" onClick={()=>void page.refetch()}>{t('retry')}</button></div>}{page.isError&&!page.data&&<ErrorState onRetry={()=>void page.refetch()}/>}
    {!page.isLoading&&page.data?.items.length===0&&<EmptyState label={t('noAcceptedRecords')}/>}
    {page.data?.items.length?<div className="card-list">{page.data.items.map(record=><article className="review-card" key={record.id}><div><strong>{record.title}</strong><span>{record.source}</span></div><p>{record.summary}</p><dl><div><dt>{t('sourceType')}</dt><dd>{record.source_type}</dd></div><div><dt>{t('processingState')}</dt><dd>{record.processing_state}</dd></div><div><dt>{t('entities')}</dt><dd>{number(record.entity_count)}</dd></div><div><dt>{t('indicators')}</dt><dd>{number(record.indicator_count)}</dd></div><div><dt>{t('correlations')}</dt><dd>{number(record.correlation_count)}</dd></div><div><dt>{t('collectedAt')}</dt><dd>{record.collected_at?dateTime(record.collected_at):t('notAvailable')}</dd></div></dl><button className="button button-secondary" onClick={event=>open(record.id,event.currentTarget)}>{t('viewDetails')}</button>{can('analyst')&&<details><summary>{t('technicalDetails')}</summary><code dir="ltr">{record.id}</code></details>}</article>)}</div>:null}
    {page.data&&page.data.total>limit&&<nav className="pagination"><button disabled={offset===0} onClick={()=>setOffset(Math.max(0,offset-limit))}>{t('previous')}</button><span>{number(offset+1)}–{number(Math.min(offset+limit,page.data.total))}</span><button disabled={offset+limit>=page.data.total} onClick={()=>setOffset(offset+limit)}>{t('next')}</button></nav>}
    {Boolean(page.data?.malformed_items)&&can('analyst')&&<details className="state-panel"><summary>{t('technicalDetails')}</summary><p>{t('malformedRecordsIgnored',{count:number(page.data!.malformed_items!)})}</p></details>}
    {selected&&<div className="record-modal-backdrop" onMouseDown={event=>{if(event.target===event.currentTarget)close()}}><div ref={dialog} className="record-modal" role="dialog" aria-modal="true" aria-labelledby="record-dialog-title" tabIndex={-1}><div className="record-modal-head"><h3 id="record-dialog-title">{detail.data?.title||t('viewDetails')}</h3><button className="modal-close" aria-label={t('close')} onClick={close}>×</button></div><div className="record-modal-body">{detail.isLoading?<LoadingState/>:detail.isError?<ErrorState onRetry={()=>void detail.refetch()}/>:detail.data&&<><dl className="record-modal-summary"><div><dt>{t('source')}</dt><dd>{detail.data.source}</dd></div><div><dt>{t('processingState')}</dt><dd>{detail.data.processing_state}</dd></div></dl><p className="record-content">{detail.data.content}</p><section><h4>{t('entities')}</h4>{detail.data.entities?.length?<ul>{detail.data.entities.map((item,index)=><li key={`${item.type}-${index}`}><strong>{item.type}</strong>: {item.value}</li>)}</ul>:<EmptyState label={t('noEntitiesIdentified')}/>}</section><section><h4>{t('indicators')}</h4>{detail.data.indicators?.length?<ul>{detail.data.indicators.map((item,index)=><li key={`${item.type}-${index}`}><strong>{item.type}</strong>: {item.value}</li>)}</ul>:<EmptyState label={t('noIndicatorsExtracted')}/>}</section><section><h4>{t('correlations')}</h4>{detail.data.correlations?.length?<ul>{detail.data.correlations.map((item,index)=><li key={`${item.type}-${index}`}><strong>{item.type}</strong>: {item.explanation}</li>)}</ul>:<EmptyState label={t('noCorrelationsFound')}/>}</section></>}</div></div></div>}
  </section>;
}
