import { type FormEvent, useState } from 'react';
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { api, ApiError, type AdminUser, type Role } from '../api/client';
import { useAuth } from '../auth/AuthContext';
import { EmptyState, ErrorState, LoadingState } from '../components/States';
import { StatusBadge } from '../components/StatusBadge';

const formatTime = (value: string) => new Intl.DateTimeFormat('ar', { dateStyle: 'medium', timeStyle: 'short' }).format(new Date(value));
function Pager({ total, offset, setOffset }: { total: number; offset: number; setOffset: (value: number) => void }) { const limit = 20; return <div className="pagination"><button className="button button-secondary" disabled={!offset} onClick={() => setOffset(Math.max(0, offset - limit))}>السابق</button><span>{total ? `${offset + 1}–${Math.min(total, offset + limit)} من ${total}` : '0'}</span><button className="button button-secondary" disabled={offset + limit >= total} onClick={() => setOffset(offset + limit)}>التالي</button></div>; }

export function AdminGuard({ children }: { children: React.ReactNode }) {
  const { user } = useAuth();
  if (user?.role !== 'admin') return <section className="page-section"><div className="state-panel error-panel" role="alert"><strong>الوصول غير مسموح</strong><span>هذه المساحة متاحة للمسؤولين فقط.</span></div></section>;
  return <>{children}</>;
}

export function AdminPage() {
  const queryClient = useQueryClient();
  const [offset, setOffset] = useState(0); const [auditOffset, setAuditOffset] = useState(0);
  const [search, setSearch] = useState(''); const [roleFilter, setRoleFilter] = useState(''); const [activeFilter, setActiveFilter] = useState('');
  const [username, setUsername] = useState(''); const [password, setPassword] = useState(''); const [role, setRole] = useState<Role>('viewer'); const [showPassword, setShowPassword] = useState(false);
  const [resetUser, setResetUser] = useState<AdminUser | null>(null); const [resetPassword, setResetPassword] = useState('');
  const users = useQuery({ queryKey: ['admin-users', offset, search, roleFilter, activeFilter], queryFn: () => api.adminUsers(20, offset, search.length >= 2 ? search : '', roleFilter, activeFilter), retry: false });
  const logs = useQuery({ queryKey: ['admin-audit', auditOffset], queryFn: () => api.adminAudit(20, auditOffset), retry: false });
  const refresh = () => { void queryClient.invalidateQueries({ queryKey: ['admin-users'] }); void queryClient.invalidateQueries({ queryKey: ['admin-audit'] }); };
  const create = useMutation({ mutationFn: (data: { username: string; password: string; role: Role }) => api.adminCreateUser(data.username, data.password, data.role), onSuccess: () => { setUsername(''); refresh(); } });
  const changeRole = useMutation({ mutationFn: ({ id, next }: { id: string; next: Role }) => api.adminChangeRole(id, next), onSuccess: refresh });
  const changeActive = useMutation({ mutationFn: ({ id, next }: { id: string; next: boolean }) => api.adminChangeActive(id, next), onSuccess: refresh });
  const reset = useMutation({ mutationFn: ({ id, password: next }: { id: string; password: string }) => api.adminResetPassword(id, next), onSuccess: () => { setResetUser(null); refresh(); } });
  function submitCreate(event: FormEvent) { event.preventDefault(); if (create.isPending || !username.trim() || password.length < 10) return; const submitted = password; setPassword(''); create.mutate({ username: username.trim(), password: submitted, role }); }
  function confirmRole(user: AdminUser, next: Role) { if (!changeRole.isPending && next !== user.role && window.confirm(`تأكيد تغيير دور ${user.username} إلى ${next}؟`)) changeRole.mutate({ id: user.id, next }); }
  function confirmActive(user: AdminUser) { if (!changeActive.isPending && window.confirm(`تأكيد ${user.is_active ? 'تعطيل' : 'تفعيل'} ${user.username}؟`)) changeActive.mutate({ id: user.id, next: !user.is_active }); }
  function submitReset(event: FormEvent) { event.preventDefault(); if (!resetUser || reset.isPending || resetPassword.length < 10) return; if (!window.confirm(`تأكيد إعادة تعيين كلمة مرور ${resetUser.username}؟`)) return; const submitted = resetPassword; setResetPassword(''); reset.mutate({ id: resetUser.id, password: submitted }); }
  const mutationError = create.error || changeRole.error || changeActive.error || reset.error;
  return <section className="page-section admin-module">
    <div className="section-heading"><div><span className="eyebrow">الإدارة / 01</span><h2>المستخدمون والتدقيق</h2><p>إدارة مركزية محدودة الصلاحيات مع سجل تدقيق آمن.</p></div></div>
    <article className="admin-form-card"><h3>إنشاء مستخدم</h3><form onSubmit={submitCreate} autoComplete="off"><div className="admin-form-grid"><label>اسم المستخدم<input value={username} onChange={(e) => setUsername(e.target.value)} pattern="[A-Za-z0-9_.-]+" minLength={3} maxLength={100} required autoComplete="off" /></label><label>الدور<select value={role} onChange={(e) => setRole(e.target.value as Role)}><option value="viewer">viewer</option><option value="analyst">analyst</option><option value="admin">admin</option></select></label><label>كلمة المرور<span className="password-field"><input aria-label="كلمة مرور المستخدم الجديد" type={showPassword ? 'text' : 'password'} value={password} onChange={(e) => setPassword(e.target.value)} minLength={10} maxLength={200} required autoComplete="new-password" /><button type="button" className="button button-quiet" aria-pressed={showPassword} onClick={() => setShowPassword(!showPassword)}>{showPassword ? 'إخفاء' : 'إظهار'}</button></span></label></div><button className="button button-primary" disabled={create.isPending}>{create.isPending ? 'جار الإنشاء...' : 'إنشاء المستخدم'}</button></form>{create.isSuccess && <p className="pull-result" role="status">تم إنشاء المستخدم دون عرض كلمة المرور.</p>}</article>
    {mutationError && <div className="form-error" role="alert">{mutationError instanceof ApiError && mutationError.status === 409 ? 'تعذر تنفيذ التغيير: يجب الحفاظ على مسؤول نشط واحد على الأقل أو أن اسم المستخدم موجود.' : mutationError instanceof ApiError && mutationError.status === 422 ? 'تحقق من صيغة الحقول وكلمة المرور.' : 'تعذر تنفيذ التغيير الإداري.'}</div>}
    <div className="records-heading"><h3>المستخدمون</h3><div className="filters"><input aria-label="بحث المستخدمين" placeholder="بحث باسم المستخدم" value={search} onChange={(e) => { setSearch(e.target.value); setOffset(0); }} /><select aria-label="تصفية الدور" value={roleFilter} onChange={(e) => { setRoleFilter(e.target.value); setOffset(0); }}><option value="">كل الأدوار</option><option value="viewer">viewer</option><option value="analyst">analyst</option><option value="admin">admin</option></select><select aria-label="تصفية الحالة" value={activeFilter} onChange={(e) => { setActiveFilter(e.target.value); setOffset(0); }}><option value="">كل الحالات</option><option value="true">نشط</option><option value="false">معطل</option></select></div></div>
    {users.isLoading && <LoadingState />}{users.isError && <ErrorState onRetry={() => void users.refetch()} />}{users.data?.items.length === 0 && <EmptyState label="لا توجد حسابات مطابقة" />}{users.data && users.data.items.length > 0 && <div className="table-shell"><table><thead><tr><th>المستخدم</th><th>الدور</th><th>الحالة</th><th>تاريخ الإنشاء</th><th>الإجراءات</th></tr></thead><tbody>{users.data.items.map((user) => <tr key={user.id}><td><strong>{user.username}</strong></td><td><select aria-label={`دور ${user.username}`} value={user.role} disabled={changeRole.isPending} onChange={(e) => confirmRole(user, e.target.value as Role)}><option value="viewer">viewer</option><option value="analyst">analyst</option><option value="admin">admin</option></select></td><td><StatusBadge status={user.is_active ? 'enabled' : 'disabled'} /></td><td>{formatTime(user.created_at)}</td><td><div className="card-actions"><button className="button button-secondary" disabled={changeActive.isPending} onClick={() => confirmActive(user)}>{user.is_active ? 'تعطيل' : 'تفعيل'}</button><button className="button button-quiet" onClick={() => { setResetUser(user); setResetPassword(''); }}>إعادة تعيين كلمة المرور</button></div></td></tr>)}</tbody></table></div>}{users.data && <Pager total={users.data.total} offset={offset} setOffset={setOffset} />}
    {resetUser && <article className="admin-form-card reset-card"><h3>إعادة تعيين كلمة مرور {resetUser.username}</h3><form onSubmit={submitReset}><label>كلمة المرور الجديدة<input aria-label="كلمة المرور الجديدة" type="password" value={resetPassword} onChange={(e) => setResetPassword(e.target.value)} minLength={10} maxLength={200} autoComplete="new-password" required /></label><div className="card-actions"><button className="button button-primary" disabled={reset.isPending}>{reset.isPending ? 'جار التحديث...' : 'تأكيد إعادة التعيين'}</button><button type="button" className="button button-secondary" onClick={() => { setResetUser(null); setResetPassword(''); }}>إلغاء</button></div></form></article>}
    <div className="records-heading"><h3>سجل التدقيق</h3></div>{logs.isLoading && <LoadingState />}{logs.isError && <ErrorState onRetry={() => void logs.refetch()} />}{logs.data?.items.length === 0 && <EmptyState label="لا توجد سجلات تدقيق" />}{logs.data && logs.data.items.length > 0 && <div className="table-shell"><table><thead><tr><th>الوقت</th><th>الفاعل</th><th>الإجراء</th><th>الهدف</th><th>النتيجة</th></tr></thead><tbody>{logs.data.items.map((item) => <tr key={item.id}><td>{formatTime(item.created_at)}</td><td>{item.actor || 'النظام'}</td><td>{item.action}</td><td>{item.target_type}{item.target_id ? ` / ${item.target_id}` : ''}</td><td><StatusBadge status={item.outcome} /></td></tr>)}</tbody></table></div>}{logs.data && <Pager total={logs.data.total} offset={auditOffset} setOffset={setAuditOffset} />}
  </section>;
}
