import { type FormEvent, useState } from 'react';
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { api, ApiError, type AdminUser, type Role } from '../api/client';
import { useAuth } from '../auth/AuthContext';
import { EmptyState, ErrorState, LoadingState } from '../components/States';
import { StatusBadge } from '../components/StatusBadge';
import { useI18n, type TranslationKey } from '../i18n/I18nContext';

function Pager({ total, offset, setOffset }: { total: number; offset: number; setOffset: (value: number) => void }) { const {t,number}=useI18n();const limit = 20; return <div className="pagination"><button className="button button-secondary" disabled={!offset} onClick={() => setOffset(Math.max(0, offset - limit))}>{t('previous')}</button><span>{total ? t('pageRange',{start:number(offset+1),end:number(Math.min(total,offset+limit)),total:number(total)}) : number(0)}</span><button className="button button-secondary" disabled={offset + limit >= total} onClick={() => setOffset(offset + limit)}>{t('next')}</button></div>; }
type Translate = (key: TranslationKey, params?: Record<string, string | number>) => string;
const roleLabel = (role: Role, t: Translate) => t(role === 'admin' ? 'administrator' : role);
const auditActionLabel = (action: string, t: Translate) => { const keys: Record<string, TranslationKey> = { admin_create_user: 'adminCreateUserAction', admin_change_role: 'adminChangeRoleAction', admin_change_active: 'adminChangeActiveAction', admin_reset_password: 'adminResetPasswordAction' }; return keys[action] ? t(keys[action]) : action; };

export function AdminGuard({ children }: { children: React.ReactNode }) {
  const {t}=useI18n();
  const { user } = useAuth();
  if (user?.role !== 'admin') return <section className="page-section"><div className="state-panel error-panel" role="alert"><strong>{t('forbidden')}</strong><span>{t('adminOnlyHint')}</span></div></section>;
  return <>{children}</>;
}

export function AdminPage() {
  const {t,dateTime}=useI18n();
  const queryClient = useQueryClient();
  const [offset, setOffset] = useState(0); const [auditOffset, setAuditOffset] = useState(0); const [auditAction, setAuditAction] = useState(''); const [auditActor, setAuditActor] = useState('');
  const [search, setSearch] = useState(''); const [roleFilter, setRoleFilter] = useState(''); const [activeFilter, setActiveFilter] = useState('');
  const [username, setUsername] = useState(''); const [password, setPassword] = useState(''); const [role, setRole] = useState<Role>('viewer'); const [showPassword, setShowPassword] = useState(false);
  const [resetUser, setResetUser] = useState<AdminUser | null>(null); const [resetPassword, setResetPassword] = useState('');
  const users = useQuery({ queryKey: ['admin-users', offset, search, roleFilter, activeFilter], queryFn: () => api.adminUsers(20, offset, search.length >= 2 ? search : '', roleFilter, activeFilter), retry: false });
  const logs = useQuery({ queryKey: ['admin-audit', auditOffset, auditAction, auditActor], queryFn: () => api.adminAudit(20, auditOffset, auditAction.length >= 2 ? auditAction : '', auditActor.length >= 2 ? auditActor : ''), retry: false });
  const refresh = () => { void queryClient.invalidateQueries({ queryKey: ['admin-users'] }); void queryClient.invalidateQueries({ queryKey: ['admin-audit'] }); };
  const create = useMutation({ mutationFn: (data: { username: string; password: string; role: Role }) => api.adminCreateUser(data.username, data.password, data.role), onSuccess: () => { setUsername(''); refresh(); } });
  const changeRole = useMutation({ mutationFn: ({ id, next }: { id: string; next: Role }) => api.adminChangeRole(id, next), onSuccess: refresh });
  const changeActive = useMutation({ mutationFn: ({ id, next }: { id: string; next: boolean }) => api.adminChangeActive(id, next), onSuccess: refresh });
  const reset = useMutation({ mutationFn: ({ id, password: next }: { id: string; password: string }) => api.adminResetPassword(id, next), onSuccess: () => { setResetUser(null); refresh(); } });
  function submitCreate(event: FormEvent) { event.preventDefault(); if (create.isPending || !username.trim() || password.length < 10) return; const submitted = password; setPassword(''); create.mutate({ username: username.trim(), password: submitted, role }); }
  function confirmRole(user: AdminUser, next: Role) { if (!changeRole.isPending && next !== user.role && window.confirm(t('confirmRoleChange',{username:user.username,role:roleLabel(next,t)}))) changeRole.mutate({ id: user.id, next }); }
  function confirmActive(user: AdminUser) { if (!changeActive.isPending && window.confirm(t('confirmUserState',{action:t(user.is_active?'disable':'enable'),username:user.username}))) changeActive.mutate({ id: user.id, next: !user.is_active }); }
  function submitReset(event: FormEvent) { event.preventDefault(); if (!resetUser || reset.isPending || resetPassword.length < 10) return; if (!window.confirm(t('confirmPasswordReset',{username:resetUser.username}))) return; const submitted = resetPassword; setResetPassword(''); reset.mutate({ id: resetUser.id, password: submitted }); }
  const mutationError = create.error || changeRole.error || changeActive.error || reset.error;
  return <section className="page-section admin-module">
    <div className="section-heading"><div><span className="eyebrow">{t('adminEyebrow')}</span><h2>{t('admin')}</h2><p>{t('adminDescription')}</p></div></div>
    <article className="admin-form-card"><h3>{t('createUser')}</h3><form onSubmit={submitCreate} autoComplete="off"><div className="admin-form-grid"><label>{t('username')}<input aria-label={t('username')} value={username} onChange={(e) => setUsername(e.target.value)} pattern="[A-Za-z0-9_.-]+" minLength={3} maxLength={100} required autoComplete="off" /></label><label>{t('role')}<select aria-label={t('role')} value={role} onChange={(e) => setRole(e.target.value as Role)}><option value="viewer">{roleLabel('viewer',t)}</option><option value="analyst">{roleLabel('analyst',t)}</option><option value="admin">{roleLabel('admin',t)}</option></select></label><label>{t('password')}<span className="password-field"><input aria-label={t('newUserPassword')} type={showPassword ? 'text' : 'password'} value={password} onChange={(e) => setPassword(e.target.value)} minLength={10} maxLength={200} required autoComplete="new-password" /><button type="button" className="button button-quiet" aria-pressed={showPassword} onClick={() => setShowPassword(!showPassword)}>{showPassword ? t('hide') : t('show')}</button></span></label></div><button className="button button-primary" disabled={create.isPending}>{create.isPending ? t('creating') : t('createUserAction')}</button></form>{create.isSuccess && <p className="pull-result" role="status">{t('userCreatedSafely')}</p>}</article>
    {mutationError && <div className="form-error" role="alert">{mutationError instanceof ApiError && mutationError.status === 409 ? t('adminConflict') : mutationError instanceof ApiError && mutationError.status === 422 ? t('adminValidation') : t('adminChangeFailed')}</div>}
    <div className="records-heading"><h3>{t('users')}</h3><div className="filters"><input aria-label={t('searchUsers')} placeholder={t('searchUsername')} value={search} onChange={(e) => { setSearch(e.target.value); setOffset(0); }} /><select aria-label={t('filterRole')} value={roleFilter} onChange={(e) => { setRoleFilter(e.target.value); setOffset(0); }}><option value="">{t('allRoles')}</option><option value="viewer">{roleLabel('viewer',t)}</option><option value="analyst">{roleLabel('analyst',t)}</option><option value="admin">{roleLabel('admin',t)}</option></select><select aria-label={t('filterActiveState')} value={activeFilter} onChange={(e) => { setActiveFilter(e.target.value); setOffset(0); }}><option value="">{t('allStates')}</option><option value="true">{t('active')}</option><option value="false">{t('inactive')}</option></select></div></div>
    {users.isLoading && <LoadingState />}{users.isError && <ErrorState onRetry={() => void users.refetch()} />}{users.data?.items.length === 0 && <EmptyState label={t('noMatchingAccounts')} />}{users.data && users.data.items.length > 0 && <div className="table-shell"><table><thead><tr><th>{t('user')}</th><th>{t('role')}</th><th>{t('status')}</th><th>{t('createdAt')}</th><th>{t('actions')}</th></tr></thead><tbody>{users.data.items.map((user) => <tr key={user.id}><td><strong>{user.username}</strong></td><td><select aria-label={t('userRoleLabel',{username:user.username})} value={user.role} disabled={changeRole.isPending} onChange={(e) => confirmRole(user, e.target.value as Role)}><option value="viewer">{roleLabel('viewer',t)}</option><option value="analyst">{roleLabel('analyst',t)}</option><option value="admin">{roleLabel('admin',t)}</option></select></td><td><StatusBadge status={user.is_active ? 'enabled' : 'disabled'} /></td><td>{dateTime(user.created_at)}</td><td><div className="card-actions"><button className="button button-secondary" disabled={changeActive.isPending} onClick={() => confirmActive(user)}>{user.is_active ? t('disable') : t('enable')}</button><button className="button button-quiet" onClick={() => { setResetUser(user); setResetPassword(''); }}>{t('resetPassword')}</button></div></td></tr>)}</tbody></table></div>}{users.data && <Pager total={users.data.total} offset={offset} setOffset={setOffset} />}
    {resetUser && <article className="admin-form-card reset-card"><h3>{t('resetPasswordFor',{username:resetUser.username})}</h3><form onSubmit={submitReset}><label>{t('newPassword')}<input aria-label={t('newPassword')} type="password" value={resetPassword} onChange={(e) => setResetPassword(e.target.value)} minLength={10} maxLength={200} autoComplete="new-password" required /></label><div className="card-actions"><button className="button button-primary" disabled={reset.isPending}>{reset.isPending ? t('updatingPassword') : t('confirmReset')}</button><button type="button" className="button button-secondary" onClick={() => { setResetUser(null); setResetPassword(''); }}>{t('cancel')}</button></div></form></article>}
    <div className="records-heading"><h3>{t('auditLog')}</h3><div className="filters"><input aria-label={t('filterAuditAction')} placeholder={t('auditAction')} value={auditAction} onChange={(e) => { setAuditAction(e.target.value); setAuditOffset(0); }} /><input aria-label={t('filterAuditActor')} placeholder={t('actor')} value={auditActor} onChange={(e) => { setAuditActor(e.target.value); setAuditOffset(0); }} /></div></div>{logs.isLoading && <LoadingState />}{logs.isError && <ErrorState onRetry={() => void logs.refetch()} />}{logs.data?.items.length === 0 && <EmptyState label={t('noAuditRecords')} />}{logs.data && logs.data.items.length > 0 && <div className="table-shell"><table><thead><tr><th>{t('time')}</th><th>{t('actor')}</th><th>{t('auditAction')}</th><th>{t('target')}</th><th>{t('outcome')}</th></tr></thead><tbody>{logs.data.items.map((item) => <tr key={item.id}><td>{dateTime(item.created_at)}</td><td>{item.actor || t('systemActor')}</td><td>{auditActionLabel(item.action,t)}</td><td>{item.target_type}{item.target_id ? ` / ${item.target_id}` : ''}</td><td>{item.outcome === 'success' ? t('successOutcome') : <StatusBadge status={item.outcome} />}</td></tr>)}</tbody></table></div>}{logs.data && <Pager total={logs.data.total} offset={auditOffset} setOffset={setAuditOffset} />}
  </section>;
}
