import { useState } from 'react';
import { useMutation, useQuery } from '@tanstack/react-query';
import { api, ApiError, type DarkWebDiscoveredSource, type DarkWebResult, type DarkWebWatch, type ExternalJob } from '../api/client';
import { useAuth } from '../auth/AuthContext';
import { useI18n } from '../i18n/I18nContext';
import { EmptyState, ErrorState, LoadingState } from '../components/States';
import { JobMonitor, TERMINAL_STATES } from './Sources';

const PAGE_SIZE=25;
function safeActionError(error:unknown,t:ReturnType<typeof useI18n>['t']){if(error instanceof ApiError&&error.status===401)return t('sessionExpired');if(error instanceof ApiError&&error.status===403)return t('forbidden');if(error instanceof ApiError&&error.status===409)return t('duplicateWatch');if(error instanceof ApiError&&error.status===422)return t('invalidWatchKeyword');if(error instanceof ApiError&&error.status===429)return t('providerUnavailable');if(error instanceof ApiError&&[502,503,504].includes(error.status))return t('darkWebUnavailable');if(error instanceof ApiError&&error.code==='invalid_response')return t('malformed');if(error instanceof TypeError)return t('disconnected');return t('watchSaveFailed')}
function Result({item,watch,onPromote,busy}:{item:DarkWebResult;watch?:DarkWebWatch;onPromote:(item:DarkWebResult)=>void;busy:boolean}){const {can}=useAuth(),{t,dateTime}=useI18n();return <article className="dark-result"><span>{t(item.status==='new'?'newResult':'knownResult')}</span><small dir="ltr">{item.onion_reference} · {item.provider}</small><h3>{item.title}</h3><p>{item.excerpt}</p>{item.matched_keywords.length>0&&<p><strong>{t('matchedKeywords')}:</strong> {item.matched_keywords.join(' · ')}</p>}<dl><div><dt>{t('firstSeen')}</dt><dd>{dateTime(item.first_seen_at)}</dd></div><div><dt>{t('lastSeen')}</dt><dd>{dateTime(item.last_seen_at)}</dd></div>{item.collected_at&&<div><dt>{t('collectedTime')}</dt><dd>{dateTime(item.collected_at)}</dd></div>}<div><dt>{t('contentFingerprint')}</dt><dd><code dir="ltr">{item.content_sha256.slice(0,12)}…{item.content_sha256.slice(-8)}</code></dd></div></dl><small>{t(item.privacy_status==='reviewed'?'privacyReviewed':'privacyReviewRequired')}</small>{can('analyst')&&watch?.provider_id&&<button disabled={busy} onClick={()=>onPromote(item)}>{t('monitorDiscovered')}</button>}</article>}
function DiscoveredSource({item,onToggle,busy}:{item:DarkWebDiscoveredSource;onToggle:(item:DarkWebDiscoveredSource)=>void;busy:boolean}){const {can}=useAuth(),{t,dateTime}=useI18n();return <article><code dir="ltr">{item.onion_reference}</code><small>{t(item.enabled?'enabled':'disabled')} · {dateTime(item.updated_at)}</small>{can('analyst')&&<button disabled={busy} onClick={()=>onToggle(item)}>{t(item.enabled?'disable':'enable')}</button>}</article>}

export function DarkWebWatches(){
  const {can}=useAuth(),{t,number,dateTime}=useI18n();
  const [input,setInput]=useState(''),[keywords,setKeywords]=useState<string[]>([]),[mode,setMode]=useState<'any'|'all'>('any'),[provider,setProvider]=useState(''),[selected,setSelected]=useState(''),[resultStatus,setResultStatus]=useState<'all'|'new'|'known'>('all'),[offset,setOffset]=useState(0),[job,setJob]=useState<ExternalJob>(),[jobWatchId,setJobWatchId]=useState(''),[message,setMessage]=useState('');
  const watches=useQuery({queryKey:['dark-web-watches'],queryFn:api.darkWebWatches,retry:false});
  const providers=useQuery({queryKey:['dark-web-providers'],queryFn:api.darkWebDiscoveryProviders,retry:false});
  const results=useQuery({queryKey:['dark-web-results',selected,offset],queryFn:()=>api.darkWebResults(selected,PAGE_SIZE,offset),enabled:Boolean(selected),retry:false});
  const discovered=useQuery({queryKey:['dark-web-discovered-sources',selected],queryFn:()=>api.darkWebDiscoveredSources(selected),enabled:Boolean(selected&&watches.data?.items.find(value=>value.watch_id===selected)?.provider_id),retry:false});
  const readyProviders=providers.data?.filter(value=>value.enabled&&value.ready)||[];
  const providerReady=readyProviders.some(value=>value.provider_id===provider);
  const normalized=input.trim().replace(/\s+/g,' '),duplicate=keywords.some(value=>value.toLocaleLowerCase()===normalized.toLocaleLowerCase());
  const create=useMutation({mutationFn:()=>api.createDarkWebDiscoveryWatch(keywords,mode,provider),onSuccess:()=>{setKeywords([]);setMessage('');void watches.refetch()}});
  const toggle=useMutation({mutationFn:({id,enabled}:{id:string;enabled:boolean})=>api.patchDarkWebWatch(id,enabled),onSuccess:()=>void watches.refetch()});
  const scan=useMutation({mutationFn:api.scanDarkWebWatch,onSuccess:(value,watchId)=>{setJobWatchId(watchId);setJob(value)}});
  const promote=useMutation({mutationFn:({watchId,resultId}:{watchId:string;resultId:string})=>api.promoteDarkWebResult(watchId,resultId),onSuccess:()=>setMessage(t('sourceMonitored'))});
  const toggleSource=useMutation({mutationFn:({sourceId,enabled}:{sourceId:string;enabled:boolean})=>api.patchDarkWebDiscoveredSource(sourceId,enabled),onSuccess:()=>void discovered.refetch()});
  const active=watches.data?.items.find(value=>value.watch_id===selected),activeJob=Boolean(job&&!TERMINAL_STATES.includes(job.state)),actionError=create.error||toggle.error||scan.error||promote.error;
  function addKeyword(){if(normalized.length<2||keywords.length>=10||duplicate)return;setKeywords(value=>[...value,normalized]);setInput('')}
  function submit(event:React.FormEvent){event.preventDefault();if(keywords.length&&providerReady&&!create.isPending&&window.confirm(t('confirmCreateWatch')))create.mutate()}
  function promoteResult(item:DarkWebResult){if(selected&&!promote.isPending&&window.confirm(t('confirmPromoteSource')))promote.mutate({watchId:selected,resultId:item.result_id})}
  function toggleDiscoveredSource(item:DarkWebDiscoveredSource){if(!toggleSource.isPending&&window.confirm(t(item.enabled?'confirmDisableSource':'confirmEnableSource')))toggleSource.mutate({sourceId:item.source_id,enabled:!item.enabled})}
  return <section className="page-section dark-web-page"><div className="section-heading"><div><span className="eyebrow">{t('darkScope')}</span><h2>{t('darkWeb')}</h2><p>{t('darkDescription')}</p><p>{t('verifiedDiscoveryHint')}</p></div></div>
    <div role="status">{providers.isLoading?t('checking'):providers.data?.some(value=>value.ready)?t('providerReady'):t('providerUnconfigured')}</div>
    {can('analyst')&&<form className="watch-form" onSubmit={submit}><label htmlFor="watch-keyword">{t('keywordChip')}</label><div><input id="watch-keyword" value={input} minLength={2} maxLength={100} onChange={event=>setInput(event.target.value)}/><button type="button" disabled={normalized.length<2||keywords.length>=10||duplicate} onClick={addKeyword}>{t('addKeyword')}</button></div><div className="keyword-chips">{keywords.map(value=><button type="button" key={value} aria-label={`${t('remove')} ${value}`} onClick={()=>setKeywords(items=>items.filter(item=>item!==value))}>{value} ×</button>)}</div><label>{t('matchMode')}<select value={mode} onChange={event=>setMode(event.target.value as 'any'|'all')}><option value="any">{t('matchAny')}</option><option value="all">{t('matchAll')}</option></select></label><label>{t('discoveryProvider')}<select value={provider} onChange={event=>setProvider(event.target.value)}><option value="">—</option>{readyProviders.map(value=><option key={value.provider_id} value={value.provider_id}>{value.provider_id}</option>)}</select></label><button disabled={create.isPending||keywords.length===0||!providerReady}>{t('add')}</button></form>}
    {actionError&&<div role="alert">{safeActionError(actionError,t)}</div>}{message&&<div role="status">{message}</div>}{watches.isLoading&&<LoadingState/>}{watches.isError&&(watches.error instanceof ApiError&&watches.error.status===503?<div role="alert">{t('darkWebUnavailable')}</div>:<ErrorState onRetry={()=>void watches.refetch()}/>)}{watches.data?.items.length===0&&<EmptyState label={t('noWatches')}/>}<div className="watch-grid">{watches.data?.items.map(w=><article key={w.watch_id}><button onClick={()=>{setSelected(w.watch_id);setOffset(0)}}><strong>{(w.keywords||[w.keyword]).join(' · ')}</strong><span>{t(w.match_mode==='all'?'matchAll':'matchAny')} · {t('newCount',{count:number(w.new_result_count)})} · {t('totalCount',{count:number(w.result_count)})}</span></button><small>{w.last_scan_at?t('lastScanAt',{value:dateTime(w.last_scan_at)}):t('notScannedYet')}</small>{can('analyst')&&<><button disabled={scan.isPending||!w.enabled||(activeJob&&jobWatchId===w.watch_id)} onClick={()=>window.confirm(t('confirmScan'))&&scan.mutate(w.watch_id)}>{w.provider_id?t('discoverScan'):t('scanNow')}</button><button disabled={toggle.isPending||(activeJob&&jobWatchId===w.watch_id)} onClick={()=>window.confirm(t(w.enabled?'confirmDisableWatch':'confirmEnableWatch'))&&toggle.mutate({id:w.watch_id,enabled:!w.enabled})}>{t(w.enabled?'disable':'enable')}</button></>}</article>)}</div>
    {job&&<JobMonitor key={job.job_id} sourceId={jobWatchId} job={job} onUpdate={(watchId,value)=>{setJob(current=>current?.job_id===value.job_id?value:current);if(TERMINAL_STATES.includes(value.state)){void watches.refetch();if(selected===watchId){void results.refetch();void discovered.refetch()}}}}/>}
    {selected&&<section><h3>{t('results')}</h3><label>{t('resultStatus')}<select value={resultStatus} onChange={event=>setResultStatus(event.target.value as 'all'|'new'|'known')}><option value="all">{t('allResults')}</option><option value="new">{t('newResult')}</option><option value="known">{t('knownResult')}</option></select></label>{results.isLoading&&<LoadingState/>}{results.isError&&<ErrorState onRetry={()=>void results.refetch()}/>} {results.data?.items.length===0&&<EmptyState label={t('noApprovedMatches')}/>} {results.data?.items.filter(item=>resultStatus==='all'||item.status===resultStatus).map(item=><Result key={item.result_id} item={item} watch={active} onPromote={promoteResult} busy={promote.isPending}/>)}{results.data&&results.data.total>0&&<nav className="pagination" aria-label={t('results')}><button disabled={offset===0} onClick={()=>setOffset(Math.max(0,offset-PAGE_SIZE))}>{t('previous')}</button><span>{t('pageRange',{start:number(offset+1),end:number(Math.min(offset+results.data.items.length,results.data.total)),total:number(results.data.total)})}</span><button disabled={offset+PAGE_SIZE>=results.data.total} onClick={()=>setOffset(offset+PAGE_SIZE)}>{t('next')}</button></nav>}{active?.provider_id&&<section><h3>{t('discoveredSources')}</h3>{discovered.isLoading&&<LoadingState/>}{discovered.isError&&<ErrorState onRetry={()=>void discovered.refetch()}/>} {discovered.data?.length===0&&<EmptyState label={t('noDiscoveredSources')}/>}<div className="watch-grid">{discovered.data?.map(item=><DiscoveredSource key={item.source_id} item={item} onToggle={toggleDiscoveredSource} busy={toggleSource.isPending}/>)}</div></section>}</section>}</section>
}
