import { useState } from 'react';
import { useMutation,useQuery } from '@tanstack/react-query';
import { api,type DarkWebResult,type ExternalJob } from '../api/client';
import { useAuth } from '../auth/AuthContext';
import { useI18n } from '../i18n/I18nContext';
import { EmptyState,ErrorState,LoadingState } from '../components/States';
import { JobMonitor } from './Sources';
function Highlight({text,keyword}:{text:string;keyword:string}){const at=text.toLocaleLowerCase().indexOf(keyword.toLocaleLowerCase());return at<0?<>{text}</>:<>{text.slice(0,at)}<mark>{text.slice(at,at+keyword.length)}</mark>{text.slice(at+keyword.length)}</>}
function Result({item,keyword}:{item:DarkWebResult;keyword:string}){const {t,dateTime}=useI18n();return <article className="dark-result"><span>{t(item.status==='new'?'newResult':'knownResult')}</span><small>{item.onion_reference} · {item.provider}</small><h3>{item.title}</h3><p><Highlight text={item.excerpt} keyword={keyword}/></p><small>{dateTime(item.first_seen_at)} · {item.privacy_status}</small></article>}
export function DarkWebWatches(){const {can}=useAuth(),{t,number}=useI18n(),[keyword,setKeyword]=useState(''),[selected,setSelected]=useState(''),[job,setJob]=useState<ExternalJob>();const watches=useQuery({queryKey:['dark-web-watches'],queryFn:api.darkWebWatches,retry:false});const results=useQuery({queryKey:['dark-web-results',selected],queryFn:()=>api.darkWebResults(selected),enabled:Boolean(selected),retry:false});const create=useMutation({mutationFn:api.createDarkWebWatch,onSuccess:()=>{setKeyword('');void watches.refetch()}});const toggle=useMutation({mutationFn:({id,enabled}:{id:string;enabled:boolean})=>api.patchDarkWebWatch(id,enabled),onSuccess:()=>void watches.refetch()});const scan=useMutation({mutationFn:api.scanDarkWebWatch,onSuccess:setJob});const active=watches.data?.items.find(x=>x.watch_id===selected);return <section className="page-section dark-web-page"><div className="section-heading"><div><span className="eyebrow">{t('darkScope')}</span><h2>{t('darkWeb')}</h2><p>{t('darkDescription')}</p></div></div>{can('analyst')&&<form className="watch-form" onSubmit={e=>{e.preventDefault();if(!create.isPending)create.mutate(keyword)}}><label htmlFor="watch-keyword">{t('watchKeyword')}</label><input id="watch-keyword" value={keyword} maxLength={100} onChange={e=>setKeyword(e.target.value)}/><button disabled={create.isPending||keyword.trim().length<2}>{t('add')}</button></form>}{create.isError&&<div role="alert">{t('watchSaveFailed')}</div>}{watches.isLoading&&<LoadingState/>}{watches.isError&&<ErrorState onRetry={()=>void watches.refetch()}/>} {watches.data?.items.length===0&&<EmptyState label={t('noWatches')}/>}<div className="watch-grid">{watches.data?.items.map(w=><article key={w.watch_id}><button onClick={()=>setSelected(w.watch_id)}><strong>{w.keyword}</strong><span>{t('newCount',{count:number(w.new_result_count)})} · {t('totalCount',{count:number(w.result_count)})}</span></button>{can('analyst')&&<><button disabled={scan.isPending||!w.enabled} onClick={()=>confirm(t('confirmScan'))&&scan.mutate(w.watch_id)}>{t('scanNow')}</button><button disabled={toggle.isPending} onClick={()=>{if(!w.enabled||confirm(t('confirmDisableWatch')))toggle.mutate({id:w.watch_id,enabled:!w.enabled})}}>{t(w.enabled?'disable':'enable')}</button></>}</article>)}</div>{job&&<JobMonitor sourceId="dark-web-watch" job={job} onUpdate={(_id,v)=>{setJob(v);if(['completed','partial','failed'].includes(v.state)){void results.refetch();void watches.refetch()}}}/>} {selected&&<section><h3>{t('results')}</h3>{results.isLoading&&<LoadingState/>}{results.isError&&<ErrorState onRetry={()=>void results.refetch()}/>} {results.data?.items.length===0&&<EmptyState label={t('noApprovedMatches')}/>} {results.data?.items.map(r=><Result key={r.result_id} item={r} keyword={active?.keyword||''}/>)}</section>}</section>}
