import { useMemo, useState } from 'react';
import { useMutation, useQuery } from '@tanstack/react-query';
import { api, ApiError, type DarkWebResult, type DarkWebWatch, type ExternalJob, type Source } from '../api/client';
import {externalQueryKeys} from '../api/externalQueryKeys';
import { useAuth } from '../auth/AuthContext';
import { useI18n } from '../i18n/I18nContext';
import { EmptyState, ErrorState, LoadingState } from '../components/States';
import { StatusBadge } from '../components/StatusBadge';
import { JobMonitor, TERMINAL_STATES } from './Sources';
import './DarkWebWatches.css';

const PAGE_SIZE=25;
const intervals=[3600,21600,43200,86400] as const;
type Interval=(typeof intervals)[number];

function safeActionError(error:unknown,t:ReturnType<typeof useI18n>['t']){
  if(error instanceof ApiError&&error.status===401)return t('sessionExpired');
  if(error instanceof ApiError&&error.status===403)return t('forbidden');
  if(error instanceof ApiError&&error.status===409)return t('duplicateWatch');
  if(error instanceof ApiError&&error.status===422)return t('invalidWatchKeyword');
  if(error instanceof ApiError&&error.status===429)return t('providerUnavailable');
  if(error instanceof ApiError&&[502,503,504].includes(error.status))return t('darkWebUnavailable');
  if(error instanceof ApiError&&error.code==='invalid_response')return t('malformed');
  if(error instanceof TypeError)return t('disconnected');
  return t('operationFailed');
}

function Schedule({watch,busy,onChange}:{watch:DarkWebWatch;busy:boolean;onChange:(enabled:boolean,interval:Interval)=>void}){
  const {t}=useI18n();
  return <div className="dark-actions dark-schedule"><label>{t('schedule')}<select aria-label={t('scheduleInterval')} value={watch.scan_interval_seconds||3600} onChange={event=>onChange(true,Number(event.target.value) as Interval)}>{intervals.map(value=><option key={value} value={value}>{value===3600?t('hourly'):value===21600?t('sixHours'):value===43200?t('twelveHours'):t('daily')}</option>)}</select></label><button className="button button-secondary" disabled={busy} onClick={()=>onChange(!watch.schedule_enabled,(watch.scan_interval_seconds||3600) as Interval)}>{t(watch.schedule_enabled?'disableSchedule':'enableSchedule')}</button></div>;
}

function ResultCard({item,onPromote,busy}:{item:DarkWebResult;onPromote:(item:DarkWebResult)=>void;busy:boolean}){
  const {can}=useAuth(),{t,dateTime}=useI18n();
  return <article className="dark-result"><div className="dark-card-head"><strong>{item.title}</strong><span className="status-pill">{t(item.status==='new'?'newResult':'knownResult')}</span></div><p>{item.excerpt}</p>{item.matched_keywords.length>0&&<p><strong>{t('matchedKeywords')}:</strong> {item.matched_keywords.join(' · ')}</p>}<dl className="dark-meta"><div><dt>{t('collectedTime')}</dt><dd>{dateTime(item.collected_at||item.last_seen_at)}</dd></div><div><dt>{t('privacy')}</dt><dd>{t(item.privacy_status==='reviewed'?'privacyReviewed':'privacyReviewRequired')}</dd></div></dl>{can('analyst')&&<div className="dark-actions"><button disabled={busy} onClick={()=>onPromote(item)}>{t('monitorDiscovered')}</button><details><summary>{t('technicalDetails')}</summary><code dir="ltr">{item.onion_reference}</code></details></div>}</article>;
}

export function DarkWebWatches(){
  const {can}=useAuth(),{t,number,dateTime}=useI18n();
  const [input,setInput]=useState(''),[keywords,setKeywords]=useState<string[]>([]),[mode,setMode]=useState<'any'|'all'>('any'),[provider,setProvider]=useState('');
  const [selected,setSelected]=useState(''),[resultOffset,setResultOffset]=useState(0),[alertOffset,setAlertOffset]=useState(0),[job,setJob]=useState<ExternalJob>(),[jobWatchId,setJobWatchId]=useState(''),[message,setMessage]=useState('');
  const watches=useQuery({queryKey:['dark-web-watches'],queryFn:api.darkWebWatches,retry:false});
  const providers=useQuery({queryKey:['dark-web-providers'],queryFn:api.darkWebDiscoveryProviders,retry:false});
  const sources=useQuery({queryKey:externalQueryKeys.sources(),queryFn:api.externalSources,retry:false});
  const results=useQuery({queryKey:['dark-web-results',selected,resultOffset],queryFn:()=>api.darkWebResults(selected,PAGE_SIZE,resultOffset),enabled:Boolean(selected),retry:false});
  const alerts=useQuery({queryKey:['dark-web-alerts',alertOffset],queryFn:()=>api.darkWebAlerts(undefined,PAGE_SIZE,alertOffset),retry:false});
  const readyProviders=providers.data?.filter(value=>value.enabled&&value.ready)||[];
  const providerReady=readyProviders.some(value=>value.provider_id===provider),discoveryReady=readyProviders.length>0;
  const directSources=useMemo(()=>sources.data?.filter(value=>value.source_type==='dark_web'||(value.source_type==='manual_url'&&value.metadata.method==='dark_web'))||[],[sources.data]);
  const discoveryWatches=useMemo(()=>watches.data?.items.filter(value=>Boolean(value.provider_id))||[],[watches.data]);
  const normalized=input.trim().replace(/\s+/g,' '),duplicate=keywords.some(value=>value.toLocaleLowerCase()===normalized.toLocaleLowerCase());
  const activeSchedules=(watches.data?.items||[]).filter(value=>value.schedule_enabled&&value.enabled).length;
  const create=useMutation({mutationFn:()=>api.createDarkWebDiscoveryWatch(keywords,mode,provider),onSuccess:()=>{setKeywords([]);setMessage('');void watches.refetch()}});
  const toggle=useMutation({mutationFn:({id,enabled}:{id:string;enabled:boolean})=>api.patchDarkWebWatch(id,enabled),onSuccess:()=>void watches.refetch()});
  const scan=useMutation({mutationFn:api.scanDarkWebWatch,onSuccess:(value,watchId)=>{setJobWatchId(watchId);setJob(value)}});
  const promote=useMutation({mutationFn:({watchId,resultId,contentSha256}:{watchId:string;resultId:string;contentSha256:string})=>api.promoteDarkWebResult(watchId,resultId,contentSha256),onSuccess:()=>{setMessage(t('sourceMonitored'));void sources.refetch()}});
  const schedule=useMutation({mutationFn:({watchId,enabled,interval}:{watchId:string;enabled:boolean;interval:Interval})=>api.patchDarkWebSchedule(watchId,enabled,interval),onSuccess:()=>void watches.refetch()});
  const readAlert=useMutation({mutationFn:api.markDarkWebAlertRead,onSuccess:()=>void alerts.refetch()});
  const runDirect=useMutation({mutationFn:(source:Source)=>api.startExternalSourceJob(source.source_id),onSuccess:(value,source)=>{setJobWatchId(source.source_id);setJob(value)}});
  const manageDirect=useMutation({mutationFn:async({source,action}:{source:Source;action:'enable'|'disable'|'archive'})=>{if(action==='enable')await api.enableExternalSource(source.source_id);else if(action==='disable')await api.disableExternalSource(source.source_id);else await api.deleteExternalSource(source.source_id)},onSuccess:()=>void sources.refetch()});
  const discoveryError=create.error||toggle.error||scan.error||promote.error||schedule.error;
  const directError=runDirect.error||manageDirect.error;
  const activeJob=Boolean(job&&!TERMINAL_STATES.includes(job.state));
  function addKeyword(){if(normalized.length<2||keywords.length>=10||duplicate)return;setKeywords(value=>[...value,normalized]);setInput('')}
  function submit(event:React.FormEvent){event.preventDefault();if(keywords.length&&providerReady&&!create.isPending&&window.confirm(t('confirmCreateWatch')))create.mutate()}
  function promoteResult(item:DarkWebResult){if(selected&&!promote.isPending&&window.confirm(t('confirmPromoteSource')))promote.mutate({watchId:selected,resultId:item.result_id,contentSha256:item.content_sha256})}
  function manage(source:Source,action:'enable'|'disable'|'archive'){if(!manageDirect.isPending&&window.confirm(t(action==='archive'?'confirmArchiveSource':action==='enable'?'confirmEnableSource':'confirmDisableSource')))manageDirect.mutate({source,action})}
  function updateJob(id:string,value:ExternalJob){setJob(current=>current?.job_id===value.job_id?value:current);if(TERMINAL_STATES.includes(value.state)){void sources.refetch();void watches.refetch();void alerts.refetch();if(selected===id)void results.refetch()}}

  return <section className="page-section dark-web-page">
    <div className="section-heading"><div><span className="eyebrow">{t('darkScope')}</span><h2>{t('darkWeb')}</h2><p>{t('darkArchitectureIntro')}</p></div></div>
    <div className="dark-explainer"><article><strong>{t('directMonitoring')}</strong><p>{t('directMonitoringExplanation')}</p></article><article><strong>{t('keywordDiscovery')}</strong><p>{t('keywordDiscoveryExplanation')}</p></article></div>
    <div className="dark-summary" aria-label={t('monitoringSummary')}><article><span>{t('directSources')}</span><strong>{number(directSources.length)}</strong></article><article><span>{t('activeSchedules')}</span><strong>{number(activeSchedules)}</strong></article><article><span>{t('unreadAlerts')}</span><strong>{number(alerts.data?.unread||0)}</strong></article><article><span>{t('discoveryProvider')}</span><strong className={discoveryReady?'summary-ok':'summary-warning'}>{t(discoveryReady?'providerReady':'providerUnavailable')}</strong></article></div>
    {message&&<div className="state-panel" role="status">{message}</div>}
    <section className="dark-section" aria-labelledby="direct-monitoring-title"><div className="dark-section-heading"><div><span className="eyebrow">{t('primaryCapability')}</span><h3 id="direct-monitoring-title">{t('directMonitoring')}</h3><p>{t('directAlwaysAvailable')}</p></div><StatusBadge status={sources.isError?'temporarily_unavailable':'ready'}/></div>
      {directError&&<div className="state-panel error-panel" role="alert">{safeActionError(directError,t)}</div>}{sources.isLoading&&<LoadingState/>}{sources.isError&&<ErrorState onRetry={()=>void sources.refetch()}/>} {!sources.isLoading&&!sources.isError&&directSources.length===0&&<EmptyState label={t('noDirectSources')}/>}<div className="direct-source-list">{directSources.map(source=><article key={source.source_id} className="direct-source-card"><div className="dark-card-head"><div><strong>{source.name}</strong><small>{t(source.metadata.origin==='promoted'?'promotedSource':'manualOnionSource')}</small></div><StatusBadge status={source.status}/></div><dl className="dark-meta"><div><dt>{t('transport')}</dt><dd>Tor / socks5h</dd></div><div><dt>{t('schedule')}</dt><dd>{t(source.metadata.origin==='promoted'?'managedByWatchSchedule':'manualRuns')}</dd></div></dl>{can('analyst')&&<div className="dark-actions"><button disabled={runDirect.isPending||source.status==='disabled'||activeJob} onClick={()=>window.confirm(t('confirmScan'))&&runDirect.mutate(source)}>{t('scanNow')}</button><button className="button button-secondary" disabled={manageDirect.isPending||activeJob} onClick={()=>manage(source,source.status==='disabled'?'enable':'disable')}>{t(source.status==='disabled'?'enable':'disable')}</button><button className="button button-danger" disabled={manageDirect.isPending||activeJob} onClick={()=>manage(source,'archive')}>{t('archive')}</button><details><summary>{t('technicalDetails')}</summary><code dir="ltr">{source.source_id}</code></details></div>}</article>)}</div>{job&&directSources.some(source=>source.source_id===jobWatchId)&&<JobMonitor key={job.job_id} sourceId={jobWatchId} label={directSources.find(source=>source.source_id===jobWatchId)?.name} job={job} onUpdate={updateJob}/>}
    </section>
    <section className="dark-section discovery-section" aria-labelledby="keyword-discovery-title"><div className="dark-section-heading"><div><span className="eyebrow">{t('optionalCapability')}</span><h3 id="keyword-discovery-title">{t('keywordDiscovery')}</h3><p>{t('verifiedDiscoveryHint')}</p></div><StatusBadge status={discoveryReady?'ready':'temporarily_unavailable'}/></div>
      {!discoveryReady&&!providers.isLoading&&<div className="discovery-notice" role="status"><strong>{t('generalDiscoveryUnavailable')}</strong></div>}{discoveryError&&<div className="state-panel error-panel" role="alert">{safeActionError(discoveryError,t)}</div>}
      {can('analyst')&&discoveryReady&&<form className="watch-form" onSubmit={submit} aria-describedby="watch-form-help"><div className="watch-form-heading"><strong>{t('addMonitoringWatch')}</strong><p id="watch-form-help">{t('watchFormHelp')}</p></div><div className="watch-keyword-field"><label htmlFor="watch-keyword">{t('keywordChip')}</label><div className="keyword-entry"><input id="watch-keyword" value={input} minLength={2} maxLength={100} aria-invalid={duplicate} aria-describedby={duplicate?'watch-keyword-error':'watch-keyword-help'} onChange={event=>setInput(event.target.value)}/><button type="button" disabled={normalized.length<2||keywords.length>=10||duplicate} onClick={addKeyword}>{t('addKeyword')}</button></div><small id="watch-keyword-help">{t('watchKeywordHelp')}</small>{duplicate&&<small id="watch-keyword-error" className="field-error" role="alert">{t('duplicateWatch')}</small>}</div><div className="keyword-chips" aria-live="polite">{keywords.map(value=><button type="button" key={value} aria-label={`${t('remove')} ${value}`} onClick={()=>setKeywords(items=>items.filter(item=>item!==value))}>{value} ×</button>)}</div><div className="watch-select-field"><label htmlFor="watch-match-mode">{t('matchMode')}</label><select id="watch-match-mode" aria-describedby="watch-match-help" value={mode} onChange={event=>setMode(event.target.value as 'any'|'all')}><option value="any">{t('matchAny')}</option><option value="all">{t('matchAll')}</option></select><small id="watch-match-help">{t('matchModeHelp')}</small></div><div className="watch-select-field"><label htmlFor="watch-provider">{t('discoveryProvider')}</label><select id="watch-provider" aria-describedby="watch-provider-help" value={provider} required onChange={event=>setProvider(event.target.value)}><option value="">—</option>{readyProviders.map(value=><option key={value.provider_id} value={value.provider_id}>{value.provider_id}</option>)}</select><small id="watch-provider-help">{t('providerSelectionHelp')}</small></div><div className="watch-schedule-preview"><span>{t('schedule')}</span><strong>{t('hourly')}</strong><small>{t('watchScheduleHelp')}</small></div><div className="watch-form-actions"><button disabled={create.isPending||keywords.length===0||!providerReady}>{create.isPending?t('submitting'):t('add')}</button></div></form>}
      {watches.isLoading&&<LoadingState/>}{watches.isError&&<ErrorState onRetry={()=>void watches.refetch()}/>} {!watches.isLoading&&!watches.isError&&discoveryWatches.length===0&&<EmptyState label={t('noWatches')}/>}<div className="discovery-watch-list">{discoveryWatches.map(watch=><article className={selected===watch.watch_id?'selected':''} key={watch.watch_id}><button className="watch-select" onClick={()=>{setSelected(watch.watch_id);setResultOffset(0)}}><strong>{(watch.keywords||[watch.keyword]).join(' · ')}</strong><span>{t(watch.match_mode==='all'?'matchAll':'matchAny')} · {t('totalCount',{count:number(watch.result_count)})}</span></button><dl className="dark-meta"><div><dt>{t('lastCheck')}</dt><dd>{watch.last_scan_at?dateTime(watch.last_scan_at):t('notScannedYet')}</dd></div><div><dt>{t('nextCheck')}</dt><dd>{watch.next_run_at?dateTime(watch.next_run_at):t('notScheduled')}</dd></div></dl>{can('analyst')&&<><div className="dark-actions"><button disabled={scan.isPending||!watch.enabled||activeJob||!discoveryReady} onClick={()=>window.confirm(t('confirmScan'))&&scan.mutate(watch.watch_id)}>{t('discoverScan')}</button><button className="button button-secondary" disabled={toggle.isPending||activeJob} onClick={()=>toggle.mutate({id:watch.watch_id,enabled:!watch.enabled})}>{t(watch.enabled?'disable':'enable')}</button></div><Schedule watch={watch} busy={schedule.isPending} onChange={(enabled,interval)=>schedule.mutate({watchId:watch.watch_id,enabled,interval})}/></>}</article>)}</div>
      {selected&&<section className="confirmed-results"><h4>{t('confirmedResults')}</h4>{results.isLoading&&<LoadingState/>}{results.isError&&<ErrorState onRetry={()=>void results.refetch()}/>} {results.data?.items.length===0&&<EmptyState label={t('noApprovedMatches')}/>}<div className="card-list">{results.data?.items.map(item=><ResultCard key={item.result_id} item={item} onPromote={promoteResult} busy={promote.isPending}/>)}</div>{results.data&&results.data.total>PAGE_SIZE&&<nav className="pagination" aria-label={t('results')}><button disabled={resultOffset===0} onClick={()=>setResultOffset(Math.max(0,resultOffset-PAGE_SIZE))}>{t('previous')}</button><span>{t('pageRange',{start:number(resultOffset+1),end:number(Math.min(resultOffset+results.data.items.length,results.data.total)),total:number(results.data.total)})}</span><button disabled={resultOffset+PAGE_SIZE>=results.data.total} onClick={()=>setResultOffset(resultOffset+PAGE_SIZE)}>{t('next')}</button></nav>}</section>}{job&&discoveryWatches.some(watch=>watch.watch_id===jobWatchId)&&<JobMonitor key={job.job_id} sourceId={jobWatchId} label={(discoveryWatches.find(watch=>watch.watch_id===jobWatchId)?.keywords||[]).join(' · ')} job={job} onUpdate={updateJob}/>}
    </section>
    <section className="dark-section" aria-labelledby="dark-alerts-title"><div className="dark-section-heading"><div><h3 id="dark-alerts-title">{t('alerts')}</h3><p>{t('alertsExplanation')}</p></div><span className="count-label">{t('unreadCount',{count:number(alerts.data?.unread||0)})}</span></div>{alerts.isLoading&&<LoadingState/>}{alerts.isError&&<ErrorState onRetry={()=>void alerts.refetch()}/>} {alerts.data?.items.length===0&&<EmptyState label={t('noAlerts')}/>}<div className="alert-list">{alerts.data?.items.map(item=><article className={item.read_at?'read':'unread'} key={item.alert_id}><div><strong>{t(item.alert_type==='new_match'?'newResult':'contentChanged')}</strong><small>{dateTime(item.created_at)}</small></div><span className="status-pill">{t(item.read_at?'read':'unread')}</span>{!item.read_at&&can('analyst')&&<button className="button button-secondary" disabled={readAlert.isPending} onClick={()=>readAlert.mutate(item.alert_id)}>{t('markRead')}</button>}{can('analyst')&&<details><summary>{t('technicalDetails')}</summary><code dir="ltr">{item.onion_reference}</code></details>}</article>)}</div>{alerts.data&&alerts.data.total>PAGE_SIZE&&<nav className="pagination" aria-label={t('alerts')}><button disabled={alertOffset===0} onClick={()=>setAlertOffset(Math.max(0,alertOffset-PAGE_SIZE))}>{t('previous')}</button><span>{t('pageRange',{start:number(alertOffset+1),end:number(Math.min(alertOffset+alerts.data.items.length,alerts.data.total)),total:number(alerts.data.total)})}</span><button disabled={alertOffset+PAGE_SIZE>=alerts.data.total} onClick={()=>setAlertOffset(alertOffset+PAGE_SIZE)}>{t('next')}</button></nav>}</section>
  </section>;
}
