import { useState } from 'react';
import { useMutation,useQuery,useQueryClient } from '@tanstack/react-query';
import { api,ApiError,type HealthResponse,type InternalIntegration } from '../api/client';
import { useAuth } from '../auth/AuthContext';
import { EmptyState,ErrorState,LoadingState } from '../components/States';
import { StatusBadge } from '../components/StatusBadge';
import { useI18n,type TranslationKey } from '../i18n/I18nContext';
const PROFILES:Record<InternalIntegration,{name:string;description:TranslationKey;type:string}>={dionaea:{name:'Dionaea',description:'dionaeaDescription',type:'dionaea_session'},'host-auth':{name:'hostAuth',description:'hostAuthDescription',type:'linux_auth_session'},'web-access':{name:'webAccess',description:'webAccessDescription',type:'web_access_session'}};
function nameFor(integration:InternalIntegration,t:(key:TranslationKey)=>string){const name=PROFILES[integration].name;return name==='Dionaea'?name:t(name as TranslationKey)}
function healthLabel(health?:HealthResponse):TranslationKey{if(!health)return'healthCheckFailed';if(!health.configured)return'unconfiguredState';if(!health.reachable)return'disconnectedState';if(health.contract_valid===false)return'degraded';return'connectedState'}
function IntegrationCard({integration,showLink=true}:{integration:InternalIntegration;showLink?:boolean}){const {can}=useAuth(),{t,number}=useI18n(),queryClient=useQueryClient(),profile=PROFILES[integration],name=nameFor(integration,t),health=useQuery({queryKey:['internal-health',integration],queryFn:()=>api.internalHealth(integration),retry:false}),pull=useMutation({mutationFn:()=>api.pullInternal(integration),onSuccess:()=>{void health.refetch();void queryClient.invalidateQueries({queryKey:['internal-events',integration]})}}),startPull=()=>{if(!pull.isPending&&window.confirm(t('confirmPull',{name})))pull.mutate()},value=health.data;return <article className="integration-card"><div className="integration-card-head"><div className="internal-icon" aria-hidden="true">◆</div><div><h3>{name}</h3><p>{t(profile.description)}</p></div><StatusBadge status={t(healthLabel(value))}/></div>{health.isLoading&&<LoadingState label={t('checkingConnection')}/>} {health.isError&&<ErrorState onRetry={()=>void health.refetch()}/>} {value&&<div className="integration-facts"><span>{t('configuration')}: <strong>{t(value.configured?'complete':'incomplete')}</strong></span><span>{t('reachability')}: <strong>{t(value.reachable?'availableAccess':'unavailableAccess')}</strong></span></div>}{value&&!value.configured&&<p className="safe-explanation">{t('internalConfigHint')}</p>}{value?.configured&&!value.reachable&&<p className="safe-explanation">{t('internalDisconnectedHint')}</p>}<div className="card-actions"><button className="button button-secondary" onClick={()=>void health.refetch()} disabled={health.isFetching}>{t('recheckSourceHealth')}</button>{can('analyst')&&<button className="button button-primary" onClick={startPull} disabled={pull.isPending||!value?.configured}>{t(pull.isPending?'pulling':'pullNow')}</button>}{showLink&&<a className="button button-quiet" href={`/internal-sources/${integration}`}>{t('viewSafeRecords')}</a>}</div>{pull.isSuccess&&<div className="pull-result" role="status">{t('pullComplete',{collected:number(pull.data.collected_count),stored:number(pull.data.stored_count)})}</div>}{pull.isError&&<div className="form-error" role="alert">{t(pull.error instanceof ApiError&&pull.error.status===403?'pullForbidden':pull.error instanceof ApiError&&pull.error.status===408?'pullTimeout':'pullFailed')}</div>}</article>}
export function InternalOverview(){const {t}=useI18n();return <section className="page-section internal-module"><div className="section-heading"><div><span className="eyebrow">{t('internalEyebrow')}</span><h2>{t('overview')}</h2><p>{t('internalOverviewDescription')}</p></div></div><div className="integration-grid">{(Object.keys(PROFILES) as InternalIntegration[]).map(key=><IntegrationCard key={key} integration={key}/>)}</div></section>}
export function InternalSourcePage({integration}:{integration:InternalIntegration}){const {t,number,dateTime}=useI18n(),profile=PROFILES[integration],[severity,setSeverity]=useState(''),[offset,setOffset]=useState(0),limit=10,events=useQuery({queryKey:['internal-events',integration,severity,offset],queryFn:()=>api.internalEvents(integration,limit,offset,severity),retry:false}),page=events.data,name=nameFor(integration,t);return <section className="page-section internal-module"><div className="section-heading"><div><span className="eyebrow">{t('internal')}</span><h2>{name}</h2><p>{t(profile.description)}</p></div></div><IntegrationCard integration={integration} showLink={false}/><div className="records-heading"><h3>{t('safeProcessedRecords')}</h3><div className="filters"><label><span className="sr-only">{t('filterSeverity')}</span><select value={severity} onChange={event=>{setSeverity(event.target.value);setOffset(0)}}><option value="">{t('allSeverities')}</option><option value="critical">{t('critical')}</option><option value="high">{t('high')}</option><option value="medium">{t('medium')}</option><option value="low">{t('low')}</option></select></label></div></div>{events.isLoading&&<LoadingState label={t('loadingSafeRecords')}/>} {events.isError&&<ErrorState onRetry={()=>void events.refetch()}/>} {page&&page.items.length===0&&<EmptyState label={t('noData')}/>} {page&&page.items.length>0&&<><div className="table-shell"><table><thead><tr><th>{t('time')}</th><th>{t('summary')}</th><th>{t('typeCategory')}</th><th>{t('severity')}</th><th>{t('source')}</th></tr></thead><tbody>{page.items.map(item=><tr key={item.id}><td>{dateTime(item.first_seen||item.created_at)}</td><td>{item.summary}</td><td><span className="type-label">{item.event_type}</span><small>{item.category||t('uncategorized')}</small></td><td><StatusBadge status={item.severity||'unknown'}/></td><td>{item.source}</td></tr>)}</tbody></table></div><div className="pagination"><button className="button button-secondary" disabled={offset===0} onClick={()=>setOffset(Math.max(0,offset-limit))}>{t('previous')}</button><span>{t('pageRange',{start:number(offset+1),end:number(Math.min(offset+limit,page.total)),total:number(page.total)})}</span><button className="button button-secondary" disabled={offset+limit>=page.total} onClick={()=>setOffset(offset+limit)}>{t('next')}</button></div></>}</section>}
