import { useState } from 'react';
import { useMutation, useQuery } from '@tanstack/react-query';
import { Link, useParams } from 'react-router-dom';
import { api, ApiError, type Page } from '../api/client';
import { useAuth } from '../auth/AuthContext';
import { EmptyState, ErrorState, LoadingState } from '../components/States';
import { StatusBadge } from '../components/StatusBadge';

const time = (value?: string) => value ? new Intl.DateTimeFormat('ar', { dateStyle: 'medium', timeStyle: 'short' }).format(new Date(value)) : 'غير متوفر';
function PageState({ query, empty, children }: { query: { isLoading: boolean; isError: boolean; refetch: () => unknown; data?: Page<unknown> }; empty: string; children: React.ReactNode }) { if (query.isLoading) return <LoadingState />; if (query.isError) return <ErrorState onRetry={() => void query.refetch()} />; if (query.data?.items.length === 0) return <EmptyState label={empty} />; return <>{children}</>; }
function Pager({ total, offset, limit, setOffset }: { total: number; offset: number; limit: number; setOffset: (value: number) => void }) { return <div className="pagination"><button className="button button-secondary" disabled={!offset} onClick={() => setOffset(Math.max(0, offset - limit))}>السابق</button><span>{total ? `${offset + 1}–${Math.min(total, offset + limit)} من ${total}` : '0'}</span><button className="button button-secondary" disabled={offset + limit >= total} onClick={() => setOffset(offset + limit)}>التالي</button></div>; }
function Heading({ eyebrow, title, text }: { eyebrow: string; title: string; text: string }) { return <div className="section-heading"><div><span className="eyebrow">{eyebrow}</span><h2>{title}</h2><p>{text}</p></div></div>; }

export function IntelligenceOverview() {
  const summary = useQuery({ queryKey: ['dashboard-summary'], queryFn: api.dashboardSummary, retry: false });
  return <section className="page-section intelligence-module"><Heading eyebrow="الاستخبارات والتحليل / 01" title="نظرة عامة" text="لقطة حالية من السجلات المركزية دون اتجاهات زمنية مصطنعة." />{summary.isLoading && <LoadingState />}{summary.isError && <ErrorState onRetry={() => void summary.refetch()} />}{summary.data && <><div className="metric-grid">{[['الأحداث', summary.data.events], ['المؤشرات', summary.data.indicators], ['الارتباطات', summary.data.correlations], ['القيم الشاذة', summary.data.outliers]].map(([label, value]) => <article className="metric-card intel-accent" key={label}><span>{label}</span><strong>{Number(value).toLocaleString('ar')}</strong></article>)}</div><div className="distribution-grid"><Distribution title="الشدة" values={summary.data.by_severity} /><Distribution title="خط المعالجة" values={summary.data.by_pipeline} /></div></>}</section>;
}
function Distribution({ title, values }: { title: string; values: Record<string, number> }) { const entries = Object.entries(values); const max = Math.max(0, ...entries.map(([, value]) => value)); return <article className="distribution-card"><h3>{title}</h3>{!entries.length ? <p>لا توجد بيانات</p> : entries.map(([label, value]) => <div className="bar-row" key={label}><div><span>{label}</span><strong>{value} سجل</strong></div><span className="bar-track"><span className="bar-fill intel-fill" style={{ width: `${max ? value / max * 100 : 0}%` }} /></span></div>)}</article>; }

export function EventsPage() {
  const [offset, setOffset] = useState(0); const [severity, setSeverity] = useState(''); const [pipeline, setPipeline] = useState(''); const [search, setSearch] = useState(''); const limit = 20;
  const query = useQuery({ queryKey: ['intel-events', offset, severity, pipeline, search], queryFn: () => api.intelligenceEvents(limit, offset, { severity, source_pipeline: pipeline, search: search.length >= 2 ? search : '' }), retry: false });
  return <section className="page-section intelligence-module"><Heading eyebrow="الاستخبارات" title="الأحداث" text="أحداث CTI المعالجة مع ملخصات آمنة وعقود عرض محدودة." /><div className="filters"><input aria-label="بحث الأحداث" placeholder="بحث في العنوان" value={search} onChange={(e) => { setSearch(e.target.value); setOffset(0); }} /><select aria-label="خط المعالجة" value={pipeline} onChange={(e) => { setPipeline(e.target.value); setOffset(0); }}><option value="">كل الخطوط</option><option value="external">خارجي</option><option value="internal">داخلي</option></select><select aria-label="الشدة" value={severity} onChange={(e) => { setSeverity(e.target.value); setOffset(0); }}><option value="">كل الشدات</option><option value="critical">حرجة</option><option value="high">عالية</option><option value="medium">متوسطة</option><option value="low">منخفضة</option></select></div><PageState query={query} empty="لا توجد أحداث"><EventTable items={query.data?.items || []} /></PageState>{query.data && <Pager total={query.data.total} offset={offset} limit={limit} setOffset={setOffset} />}</section>;
}
function EventTable({ items }: { items: Awaited<ReturnType<typeof api.intelligenceEvents>>['items'] }) { return <div className="table-shell"><table><thead><tr><th>الحدث</th><th>المصدر</th><th>الشدة</th><th>الحالة</th><th>الوقت</th></tr></thead><tbody>{items.map((item) => <tr key={item.id}><td><Link to={`/intelligence/events/${item.id}`}><strong>{item.title}</strong></Link><small>{item.summary}</small></td><td>{item.source_type}<small>{item.source_pipeline}</small></td><td><StatusBadge status={item.severity || 'unknown'} /></td><td>{item.processing_status}</td><td>{time(item.first_seen || item.created_at)}</td></tr>)}</tbody></table></div>; }

export function EventDetailPage() { const { eventId = '' } = useParams(); const query = useQuery({ queryKey: ['intel-event', eventId], queryFn: () => api.intelligenceEvent(eventId), retry: false }); const [downloaded, setDownloaded] = useState(false); async function downloadSTIX() { const bundle = await api.stixBundle(eventId); const url = URL.createObjectURL(new Blob([JSON.stringify(bundle, null, 2)], { type: 'application/json' })); const link = document.createElement('a'); link.href = url; link.download = `cti-${eventId}.stix.json`; link.click(); URL.revokeObjectURL(url); setDownloaded(true); } return <section className="page-section intelligence-module"><Heading eyebrow="تفاصيل الحدث" title={query.data?.title || 'الحدث'} text="تفاصيل تحليلية من الإسقاط المركزي الآمن." />{query.isLoading && <LoadingState />}{query.isError && <ErrorState onRetry={() => void query.refetch()} />}{query.data && <><article className="detail-panel"><p>{query.data.summary}</p><div className="integration-facts"><span>الشدة: <strong>{query.data.severity || 'غير محددة'}</strong></span><span>المخاطر: <strong>{query.data.risk_score}</strong></span><span>الثقة: <strong>{Math.round(query.data.confidence * 100)}%</strong></span></div><button className="button button-secondary" onClick={() => void downloadSTIX()}>تنزيل STIX</button>{downloaded && <span role="status" className="copy-feedback">تم تجهيز ملف STIX.</span>}</article><DetailList title="المؤشرات" items={query.data.indicators.map((item) => `${item.type}: ${['ipv4', 'ipv6', 'email', 'url'].includes(item.type) ? '••••••••' : item.value}`)} /><DetailList title="الكيانات" items={query.data.entities.map((item) => `${item.type}: ${item.value}`)} /><DetailList title="العلاقات" items={query.data.relationships.map((item) => `${item.subject} — ${item.relation} — ${item.object}`)} /></>}</section>; }
function DetailList({ title, items }: { title: string; items: string[] }) { return <section className="detail-list"><h3>{title}</h3>{items.length ? <ul>{items.map((item, index) => <li key={`${index}-${item}`}>{item}</li>)}</ul> : <p>لا توجد بيانات</p>}</section>; }

export function IndicatorsPage() { const [offset, setOffset] = useState(0); const [type, setType] = useState(''); const [search, setSearch] = useState(''); const [copied, setCopied] = useState(''); const limit = 20; const query = useQuery({ queryKey: ['indicators', offset, type, search], queryFn: () => api.intelligenceIndicators(limit, offset, type, search.length >= 2 ? search : ''), retry: false }); async function copy(id: string, value: string) { await navigator.clipboard.writeText(value); setCopied(id); } return <section className="page-section intelligence-module"><Heading eyebrow="الاستخبارات" title="المؤشرات" text="قيم CTI المصرح بها؛ تُحجب القيم على الشاشة افتراضيًا للأنواع الشبكية الحساسة." /><div className="filters"><input aria-label="بحث المؤشرات" value={search} onChange={(e) => { setSearch(e.target.value); setOffset(0); }} placeholder="بحث في القيمة" /><input aria-label="نوع المؤشر" value={type} onChange={(e) => { setType(e.target.value); setOffset(0); }} placeholder="النوع، مثل cve" /></div><PageState query={query} empty="لا توجد مؤشرات"><div className="table-shell"><table><thead><tr><th>النوع</th><th>القيمة</th><th>الثقة</th><th>المصدر</th><th>إجراء</th></tr></thead><tbody>{query.data?.items.map((item) => { const sensitive = ['ipv4', 'ipv6', 'email', 'url'].includes(item.type); return <tr key={item.id}><td>{item.type}</td><td><code>{sensitive ? '••••••••' : item.value}</code></td><td>{Math.round(item.confidence * 100)}%</td><td>{item.source_pipeline}</td><td><button className="button button-quiet" onClick={() => void copy(item.id, item.value)}>نسخ</button>{copied === item.id && <span role="status">تم النسخ</span>}</td></tr>; })}</tbody></table></div></PageState>{query.data && <Pager total={query.data.total} offset={offset} limit={limit} setOffset={setOffset} />}</section>; }

export function CorrelationsPage() { const [offset, setOffset] = useState(0); const limit = 20; const query = useQuery({ queryKey: ['correlations', offset], queryFn: () => api.intelligenceCorrelations(limit, offset), retry: false }); return <SimpleListPage title="الارتباطات" text="علاقات مخزنة فعلية بين أحداث المصدر والهدف." query={query} offset={offset} limit={limit} setOffset={setOffset} headers={['المصدر', 'الهدف', 'النوع', 'الدرجة', 'السبب']} rows={query.data?.items.map((item) => [item.source_event_id, item.target_event_id, item.type, `${Math.round(item.score * 100)}%`, item.reason]) || []} />; }
export function OutliersPage() { const [offset, setOffset] = useState(0); const limit = 20; const query = useQuery({ queryKey: ['outliers', offset], queryFn: () => api.intelligenceOutliers(limit, offset), retry: false }); return <SimpleListPage title="القيم الشاذة" text="نتائج كشف الشذوذ دون عناوين IP أو خصائص جلسة خام." query={query} offset={offset} limit={limit} setOffset={setOffset} headers={['البداية', 'النهاية', 'التنبيهات', 'الدرجة', 'الحالة']} rows={query.data?.items.map((item) => [time(item.started_at), time(item.ended_at), String(item.alert_count), item.anomaly_score.toFixed(3), item.is_outlier ? 'شاذ' : 'طبيعي']) || []} />; }
function SimpleListPage({ title, text, query, offset, limit, setOffset, headers, rows }: { title: string; text: string; query: ReturnType<typeof useQuery<Page<unknown>>>; offset: number; limit: number; setOffset: (v: number) => void; headers: string[]; rows: string[][] }) { return <section className="page-section intelligence-module"><Heading eyebrow="الاستخبارات" title={title} text={text} /><PageState query={query} empty="لا توجد بيانات"><div className="table-shell"><table><thead><tr>{headers.map((item) => <th key={item}>{item}</th>)}</tr></thead><tbody>{rows.map((row, index) => <tr key={index}>{row.map((cell, cellIndex) => <td key={cellIndex}>{cell}</td>)}</tr>)}</tbody></table></div></PageState>{query.data && <Pager total={query.data.total} offset={offset} limit={limit} setOffset={setOffset} />}</section>; }

export function AnalysisPage() { const ml = useQuery({ queryKey: ['ml-status'], queryFn: api.mlStatus, retry: false }); const runs = useQuery({ queryKey: ['analysis-runs'], queryFn: () => api.analysisRuns(50), retry: false }); const [selected, setSelected] = useState(''); const detail = useQuery({ queryKey: ['analysis-run', selected], queryFn: () => api.analysisRun(selected), enabled: Boolean(selected), retry: false }); return <section className="page-section analysis-module"><Heading eyebrow="التحليل / ML" title="عمليات التحليل" text="يعمل BERT/NER داخل Central Backend مباشرة؛ لا توجد قائمة انتظار أو خدمة عامل مستقلة." />{ml.isLoading && <LoadingState />}{ml.isError && <ErrorState onRetry={() => void ml.refetch()} />}{ml.data && <div className="metric-grid"><article className="metric-card analysis-accent"><span>Backend التحليل</span><strong>{ml.data.backend}</strong><small>{ml.data.primary_model}</small></article><article className="metric-card"><span>النموذج الأساسي</span><strong>{ml.data.primary_loaded ? 'متاح' : 'غير متاح'}</strong></article><article className="metric-card"><span>بوابات الجودة</span><strong>{ml.data.quality_gates_passed ? 'ناجحة' : 'غير مكتملة'}</strong></article></div>}<h3 className="subheading">سجل التشغيلات</h3>{runs.isLoading && <LoadingState />}{runs.isError && <ErrorState onRetry={() => void runs.refetch()} />}{runs.data?.items.length === 0 && <EmptyState label="لا توجد تشغيلات تحليل" />}{runs.data && runs.data.items.length > 0 && <div className="table-shell"><table><thead><tr><th>التشغيل</th><th>الخط</th><th>الحالة</th><th>المعالجة</th><th>المدة</th></tr></thead><tbody>{runs.data.items.map((run) => <tr key={run.id} tabIndex={0} onClick={() => setSelected(run.id)} onKeyDown={(e) => { if (e.key === 'Enter') setSelected(run.id); }}><td><button className="button button-quiet">{run.id.slice(0, 8)}</button></td><td>{run.pipeline}</td><td><StatusBadge status={run.status} /></td><td>{run.processed} / {run.failed}</td><td>{run.duration_seconds === undefined ? 'قيد التشغيل' : `${run.duration_seconds.toFixed(1)} ث`}</td></tr>)}</tbody></table></div>}{detail.isLoading && <LoadingState label="جار تحميل تفاصيل التشغيل..." />}{detail.data && <article className="detail-panel"><h3>تفاصيل التشغيل المحدد</h3><p>جُمعت {detail.data.collected}، عولجت {detail.data.processed}، خُزنت {detail.data.stored}، وفشلت {detail.data.failed}.</p>{detail.data.error_category && <p>فئة الخطأ: {detail.data.error_category}</p>}</article>}</section>; }

export function MISPPage() { const { user } = useAuth(); const health = useQuery({ queryKey: ['misp-health'], queryFn: api.mispHealth, retry: false }); const events = useQuery({ queryKey: ['misp-events'], queryFn: () => api.intelligenceEvents(50), retry: false }); const [eventId, setEventId] = useState(''); const preview = useQuery({ queryKey: ['misp-preview', eventId], queryFn: () => api.mispPreview(eventId), enabled: Boolean(eventId), retry: false }); const send = useMutation({ mutationFn: () => api.mispSend(eventId) }); function confirmSend() { if (!send.isPending && window.confirm('هل تريد إرسال هذا الحدث إلى MISP؟ لن يُنشر تلقائيًا.')) send.mutate(); } return <section className="page-section misp-module"><Heading eyebrow="المشاركة / MISP" title="MISP" text="المعاينة للقراءة فقط. الإرسال الفعلي متاح للمسؤول ويتطلب تأكيدًا صريحًا." />{health.isLoading && <LoadingState />}{health.isError && <ErrorState onRetry={() => void health.refetch()} />}{health.data && <article className="health-card misp-accent"><span>حالة MISP</span><strong>{!health.data.configured ? 'غير مهيأ' : health.data.reachable ? 'متصل' : 'غير متصل'}</strong><StatusBadge status={health.data.reachable ? 'healthy' : health.data.configured ? 'unavailable' : 'disabled'} /></article>}<label className="select-block">الحدث<select value={eventId} onChange={(e) => setEventId(e.target.value)}><option value="">اختر حدثًا للمعاينة</option>{events.data?.items.map((event) => <option value={event.id} key={event.id}>{event.title}</option>)}</select></label>{preview.isLoading && <LoadingState label="جار إعداد المعاينة..." />}{preview.isError && <ErrorState onRetry={() => void preview.refetch()} />}{preview.data && <article className="detail-panel"><h3>{preview.data.title}</h3><p>التوزيع: خاص · النشر التلقائي: لا · السمات: {preview.data.attributes.length}</p>{preview.data.attributes.length ? <ul>{preview.data.attributes.map((item, index) => <li key={`${item.type}-${index}`}><strong>{item.type}</strong>: {item.value} <small>({item.category})</small></li>)}</ul> : <p>لا توجد سمات قابلة للنقل.</p>}{user?.role === 'admin' && <button className="button button-primary" disabled={send.isPending || !preview.data.configured} onClick={confirmSend}>{send.isPending ? 'جار الإرسال...' : 'إرسال إلى MISP'}</button>}</article>}{send.isSuccess && <div className="pull-result" role="status">اكتمل التحقق من {send.data.attributes_verified} سمة. النشر: {send.data.published ? 'نعم' : 'لا'}.</div>}{send.isError && <div className="form-error" role="alert">{send.error instanceof ApiError && send.error.status === 403 ? 'الإرسال متاح للمسؤول فقط.' : 'تعذر إرسال الحدث بأمان.'}</div>}<div className="notice"><span className="notice-mark">i</span><div><strong>السجل التاريخي غير متاح</strong><p>لا يوجد حاليًا عقد Backend محدود لسجل إرسال MISP.</p></div></div></section>; }
