import { useState } from 'react';
import { useMutation, useQuery } from '@tanstack/react-query';
import { Link, useParams } from 'react-router-dom';
import { api, ApiError, type Page } from '../api/client';
import { useAuth } from '../auth/AuthContext';
import { EmptyState, ErrorState, LoadingState } from '../components/States';
import { StatusBadge } from '../components/StatusBadge';
import { useI18n,type TranslationKey } from '../i18n/I18nContext';

function PageState({ query, empty, children }: { query: { isLoading: boolean; isError: boolean; refetch: () => unknown; data?: Page<unknown> }; empty: string; children: React.ReactNode }) { if (query.isLoading) return <LoadingState />; if (query.isError) return <ErrorState onRetry={() => void query.refetch()} />; if (query.data?.items.length === 0) return <EmptyState label={empty} />; return <>{children}</>; }
function Pager({ total, offset, limit, setOffset }: { total: number; offset: number; limit: number; setOffset: (value: number) => void }) { const {t,number}=useI18n();return <div className="pagination"><button className="button button-secondary" disabled={!offset} onClick={() => setOffset(Math.max(0, offset - limit))}>{t('previous')}</button><span>{total?t('pageRange',{start:number(offset+1),end:number(Math.min(total,offset+limit)),total:number(total)}):number(0)}</span><button className="button button-secondary" disabled={offset + limit >= total} onClick={() => setOffset(offset + limit)}>{t('next')}</button></div>; }
function Heading({ eyebrow, title, text }: { eyebrow: string; title: string; text: string }) { return <div className="section-heading"><div><span className="eyebrow">{eyebrow}</span><h2>{title}</h2><p>{text}</p></div></div>; }

export function IntelligenceOverview() {
  const {t,number}=useI18n();
  const summary = useQuery({ queryKey: ['dashboard-summary'], queryFn: api.dashboardSummary, retry: false });
  return <section className="page-section intelligence-module"><Heading eyebrow={t('intelligenceEyebrow')} title={t('overview')} text={t('intelligenceSnapshot')} />{summary.isLoading && <LoadingState />}{summary.isError && <ErrorState onRetry={() => void summary.refetch()} />}{summary.data && <><div className="metric-grid">{[[t('events'), summary.data.events], [t('allObservables'), summary.data.observables], [t('verifiedIndicators'), summary.data.indicators], [t('correlations'), summary.data.correlations], [t('outliers'), summary.data.outliers]].map(([label, value]) => <article className="metric-card intel-accent" key={label}><span>{label}</span><strong>{number(Number(value))}</strong></article>)}</div><div className="distribution-grid"><Distribution title={t('severity')} values={summary.data.by_severity} /><Distribution title={t('pipeline')} values={summary.data.by_pipeline} /></div></>}</section>;
}
function Distribution({ title, values }: { title: string; values: Record<string, number> }) { const {t,number}=useI18n(),entries=Object.entries(values),max=Math.max(0,...entries.map(([,value])=>value));return <article className="distribution-card"><h3>{title}</h3>{!entries.length?<p>{t('noData')}</p>:entries.map(([label,value])=><div className="bar-row" key={label}><div><span>{label}</span><strong>{t('recordCount',{count:number(value)})}</strong></div><span className="bar-track" role="img" aria-label={`${label}: ${number(value)}`}><span className="bar-fill intel-fill" style={{width:`${max?value/max*100:0}%`}}/></span></div>)}</article>}

export function EventsPage() {
  const {t}=useI18n();
  const [offset, setOffset] = useState(0); const [severity, setSeverity] = useState(''); const [pipeline, setPipeline] = useState(''); const [search, setSearch] = useState(''); const limit = 20;
  const query = useQuery({ queryKey: ['intel-events', offset, severity, pipeline, search], queryFn: () => api.intelligenceEvents(limit, offset, { severity, source_pipeline: pipeline, search: search.length >= 2 ? search : '' }), retry: false });
  return <section className="page-section intelligence-module"><Heading eyebrow={t('intelligence')} title={t('events')} text={t('eventsDescription')} /><div className="filters"><input aria-label={t('searchEvents')} placeholder={t('searchTitle')} value={search} onChange={(e) => { setSearch(e.target.value); setOffset(0); }} /><select aria-label={t('pipeline')} value={pipeline} onChange={(e) => { setPipeline(e.target.value); setOffset(0); }}><option value="">{t('allPipelines')}</option><option value="external">{t('externalPipeline')}</option><option value="internal">{t('internalPipeline')}</option></select><select aria-label={t('severity')} value={severity} onChange={(e) => { setSeverity(e.target.value); setOffset(0); }}><option value="">{t('allSeverityLevels')}</option><option value="critical">{t('critical')}</option><option value="high">{t('high')}</option><option value="medium">{t('medium')}</option><option value="low">{t('low')}</option></select></div><PageState query={query} empty={t('noEvents')}><EventTable items={query.data?.items || []} /></PageState>{query.data && <Pager total={query.data.total} offset={offset} limit={limit} setOffset={setOffset} />}</section>;
}
function EventTable({ items }: { items: Awaited<ReturnType<typeof api.intelligenceEvents>>['items'] }) { const {t,dateTime}=useI18n();return <div className="table-shell"><table><thead><tr><th>{t('event')}</th><th>{t('source')}</th><th>{t('severity')}</th><th>{t('status')}</th><th>{t('time')}</th></tr></thead><tbody>{items.map((item) => <tr key={item.id}><td><Link to={`/intelligence/events/${item.id}`}><strong>{item.title}</strong></Link><small>{item.summary}</small></td><td>{item.source_type}<small>{item.source_pipeline}</small></td><td><StatusBadge status={item.severity || 'unknown'} /></td><td>{localizedProcessingState(item.processing_status,t)}</td><td>{dateTime(item.first_seen || item.created_at)}</td></tr>)}</tbody></table></div>; }

export function EventDetailPage() { const {t,number}=useI18n();const { eventId = '' } = useParams(); const query = useQuery({ queryKey: ['intel-event', eventId], queryFn: () => api.intelligenceEvent(eventId), retry: false }); const attack = useQuery({ queryKey: ['attack-event', eventId], queryFn: () => api.attackMapping(eventId), enabled: Boolean(eventId), retry: false }); const stix = useMutation({ mutationFn: () => api.stixBundle(eventId), onSuccess: (bundle) => { const url = URL.createObjectURL(new Blob([JSON.stringify(bundle, null, 2)], { type: 'application/json' })); const link = document.createElement('a'); link.href = url; link.download = `cti-${eventId}.stix.json`; link.click(); URL.revokeObjectURL(url); } }); return <section className="page-section intelligence-module"><Heading eyebrow={t('eventDetails')} title={query.data?.title || t('eventFallback')} text={t('eventDetailsDescription')} />{query.isLoading && <LoadingState />}{query.isError && <ErrorState onRetry={() => void query.refetch()} />}{query.data && <><article className="detail-panel"><p>{query.data.summary}</p><div className="integration-facts"><span>{t('severity')}: <strong>{localizedSeverity(query.data.severity,t)}</strong></span><span>{t('risk')}: <strong>{number(query.data.risk_score)}</strong></span><span>{t('confidence')}: <strong>{number(Math.round(query.data.confidence * 100))}%</strong></span></div><button className="button button-secondary" disabled={stix.isPending} onClick={() => stix.mutate()}>{stix.isPending ? t('preparingStix') : t('downloadStix')}</button>{stix.isSuccess && <span role="status" className="copy-feedback">{t('stixReady')}</span>}{stix.isError && <div className="form-error" role="alert">{t('stixFailed')}</div>}</article><DetailList title={t('observableAssessment')} items={query.data.indicators.map((item) => `${localizedRoleLabel(item.semantic_role,t)} · ${localizedAssessmentLabel(item.assessment,t)} · ${item.type}: ${item.value}`)} /><DetailList title={t('entities')} items={query.data.entities.map((item) => `${item.type}: ${item.value}`)} /><DetailList title={t('relationships')} items={query.data.relationships.map((item) => `${item.subject} — ${item.relation} — ${item.object}`)} />{attack.data && <AttackResults data={attack.data} />}{attack.isError && <div className="notice"><span className="notice-mark">i</span><div><strong>{t('attackAnalysisFailed')}</strong><p>{t('attackFailureNonBlocking')}</p></div></div>}</>}</section>; }
function DetailList({ title, items }: { title: string; items: string[] }) { const {t}=useI18n();return <section className="detail-list"><h3>{title}</h3>{items.length ? <ul>{items.map((item, index) => <li key={`${index}-${item}`}>{item}</li>)}</ul> : <p>{t('noData')}</p>}</section>; }

type Translate = (key: TranslationKey, values?: Record<string, string | number>) => string;
const localizedSeverity = (value: string | null | undefined, t: Translate) => value && ['critical','high','medium','low'].includes(value) ? t(value as TranslationKey) : value || t('unspecifiedState');
const localizedProcessingState = (value: string, t: Translate) => value === 'transformed' ? t('transformed') : value;
const localizedRoleLabel = (value: string, t: Translate) => { const keys: Record<string, TranslationKey> = { external_reference: 'externalReference', vulnerability: 'vulnerability', observable: 'observable', indicator: 'threatIndicator' }; return keys[value] ? t(keys[value]) : value; };
const localizedAssessmentLabel = (value: string, t: Translate) => { const keys: Record<string, TranslationKey> = { reference: 'referenceOnly', non_actionable: 'nonActionable', unknown: 'unknownAssessment', suspicious: 'suspicious', malicious: 'malicious' }; return keys[value] ? t(keys[value]) : value; };

const roleLabel = localizedRoleLabel;
const assessmentLabel = localizedAssessmentLabel;
const reasonLabel = (value: string, t: Translate) => { const keys: Record<string, TranslationKey> = { embedded_in_url: 'embeddedInUrl', reference_host: 'referenceHost', vulnerability_id: 'vulnerabilityId', non_global_ip: 'nonGlobalIp', non_global_url_host: 'nonGlobalUrlHost', reserved_domain: 'reservedDomain', locally_administered_mac: 'locallyAdministeredMac', needs_enrichment: 'needsEnrichment', enrichment_verdict: 'enrichmentVerdict', unsupported_type: 'unsupportedType' }; return keys[value] ? t(keys[value]) : value; };

export function IndicatorsPage() {
  const {t,number}=useI18n();
  const [offset, setOffset] = useState(0); const [type, setType] = useState(''); const [role, setRole] = useState(''); const [assessment, setAssessment] = useState(''); const [validation, setValidation] = useState(''); const [search, setSearch] = useState(''); const [copied, setCopied] = useState(''); const limit = 20;
  const summary = useQuery({ queryKey: ['indicator-summary'], queryFn: api.intelligenceIndicatorSummary, retry: false });
  const filters = { type, semantic_role: role, assessment, validation_status: validation, search: search.length >= 2 ? search : '' };
  const query = useQuery({ queryKey: ['indicators', offset, filters], queryFn: () => api.intelligenceIndicators(limit, offset, filters), retry: false });
  async function copy(id: string, value: string) { await navigator.clipboard.writeText(value); setCopied(id); }
  return <section className="page-section intelligence-module"><Heading eyebrow={t('intelligence')} title={t('indicators')} text={t('indicatorsDescription')} />
    {summary.data && <div className="metric-grid compact-metrics">{[[t('allValues'), summary.data.total], [t('observableValues'), summary.data.by_role.observable || 0], [t('externalReferences'), summary.data.by_role.external_reference || 0], [t('vulnerabilities'), summary.data.by_role.vulnerability || 0], [t('verifiedIndicators'), summary.data.by_role.indicator || 0]].map(([label, value]) => <article className="metric-card intel-accent" key={label}><span>{label}</span><strong>{number(Number(value))}</strong></article>)}</div>}
    <div className="notice indicator-notice"><span className="notice-mark">i</span><div><strong>{t('extractionConfidenceNotice')}</strong><p>{t('indicatorPromotionNotice')}</p></div></div>
    <div className="filters"><input aria-label={t('searchIndicators')} value={search} onChange={(e) => { setSearch(e.target.value); setOffset(0); }} placeholder={t('searchValue')} /><input aria-label={t('indicatorType')} value={type} onChange={(e) => { setType(e.target.value); setOffset(0); }} placeholder={t('indicatorTypeHint')} /><select aria-label={t('semanticRole')} value={role} onChange={(e) => { setRole(e.target.value); setOffset(0); }}><option value="">{t('allRoles')}</option><option value="observable">{t('observable')}</option><option value="external_reference">{t('externalReference')}</option><option value="vulnerability">{t('vulnerability')}</option><option value="indicator">{t('threatIndicator')}</option></select><select aria-label={t('assessment')} value={assessment} onChange={(e) => { setAssessment(e.target.value); setOffset(0); }}><option value="">{t('allAssessments')}</option><option value="unknown">{t('unknownAssessment')}</option><option value="reference">{t('referenceOnly')}</option><option value="non_actionable">{t('nonActionable')}</option><option value="suspicious">{t('suspicious')}</option><option value="malicious">{t('malicious')}</option></select><select aria-label={t('valueValidity')} value={validation} onChange={(e) => { setValidation(e.target.value); setOffset(0); }}><option value="">{t('allFormats')}</option><option value="valid">{t('valid')}</option><option value="invalid">{t('invalid')}</option></select></div>
    <PageState query={query} empty={t('noMatchingValues')}><div className="table-shell"><table className="indicator-table"><thead><tr><th>{t('type')}</th><th>{t('value')}</th><th>{t('roleAndAssessment')}</th><th>{t('extractionConfidence')}</th><th>{t('evidence')}</th><th>{t('source')}</th><th>{t('action')}</th></tr></thead><tbody>{query.data?.items.map((item) => <tr key={item.id}><td>{item.type}</td><td><Link to={`/intelligence/events/${item.event_id}`}><code className="indicator-value" dir="ltr">{item.value}</code></Link></td><td><StatusBadge status={item.actionable ? 'warning' : item.validation_status === 'invalid' ? 'unavailable' : 'healthy'} /><strong className="assessment-title">{roleLabel(item.semantic_role,t)}</strong><small>{assessmentLabel(item.assessment,t)} · {reasonLabel(item.reason_code,t)}</small></td><td>{number(Math.round(item.confidence * 100))}%<small>{t('extractionOnly')}</small></td><td>{item.evidence_count ? item.evidence_providers.join(', ') : t('noneRecorded')}<small>{number(Math.round(item.assessment_confidence * 100))}% {t('assessmentConfidence')}</small></td><td>{item.source_pipeline}</td><td><button className="button button-quiet" onClick={() => void copy(item.id, item.value)}>{t('copy')}</button>{copied === item.id && <span role="status">{t('copied')}</span>}</td></tr>)}</tbody></table></div></PageState>{query.data && <Pager total={query.data.total} offset={offset} limit={limit} setOffset={setOffset} />}</section>;
}

function AttackResults({ data }: { data: Awaited<ReturnType<typeof api.attackMapping>> }) { const {t,number}=useI18n();return <section className="detail-list attack-results"><div className="attack-heading"><h3>MITRE ATT&amp;CK</h3><a href={data.official_dataset_url} target="_blank" rel="noreferrer">{data.catalog_version}</a></div>{data.techniques.length ? <div className="attack-grid">{data.techniques.map((item) => <article key={item.technique_id}><a href={item.url} target="_blank" rel="noreferrer"><strong dir="ltr">{item.technique_id}</strong> · {item.name}</a><span>{item.tactic} · {item.mapping_source === 'explicit_id' ? t('explicitIdentifier') : t('automatedReviewCandidate')} · {number(Math.round(item.confidence * 100))}%</span><p>{item.evidence}</p></article>)}</div> : <p>{t('noSupportedTechnique')}</p>}</section>; }

export function AttackPage() { const {t}=useI18n();const [eventOffset, setEventOffset] = useState(0); const [eventSearch, setEventSearch] = useState(''); const [eventId, setEventId] = useState(''); const eventLimit = 20; const events = useQuery({ queryKey: ['attack-events', eventOffset, eventSearch], queryFn: () => api.intelligenceEvents(eventLimit, eventOffset, { search: eventSearch.length >= 2 ? eventSearch : '' }), retry: false }); const mapping = useQuery({ queryKey: ['attack-mapping', eventId], queryFn: () => api.attackMapping(eventId), enabled: Boolean(eventId), retry: false }); return <section className="page-section intelligence-module"><Heading eyebrow={t('attackEyebrow')} title="MITRE ATT&CK" text={t('attackDescription')} /><div className="select-block"><label htmlFor="attack-event-search">{t('searchEvents')}</label><input id="attack-event-search" value={eventSearch} onChange={(e) => { setEventSearch(e.target.value); setEventOffset(0); setEventId(''); }} placeholder={t('minimumTwoCharacters')} /><label htmlFor="attack-event-select">{t('event')}</label><select id="attack-event-select" value={eventId} onChange={(e) => setEventId(e.target.value)}><option value="">{t('chooseEventForAnalysis')}</option>{events.data?.items.map((event) => <option value={event.id} key={event.id}>{event.title}</option>)}</select></div>{events.isLoading && <LoadingState label={t('loadingEvents')} />}{events.isError && <ErrorState onRetry={() => void events.refetch()} />}{events.data?.items.length === 0 && <EmptyState label={t('noEvents')} />}{events.data && <Pager total={events.data.total} offset={eventOffset} limit={eventLimit} setOffset={(value) => { setEventOffset(value); setEventId(''); }} />}{mapping.isLoading && <LoadingState label={t('mappingAttack')} />}{mapping.isError && <ErrorState onRetry={() => void mapping.refetch()} />}{mapping.data && <AttackResults data={mapping.data} />}</section>; }

export function CorrelationsPage() { const {t,number}=useI18n();const [offset, setOffset] = useState(0); const limit = 20; const query = useQuery({ queryKey: ['correlations', offset], queryFn: () => api.intelligenceCorrelations(limit, offset), retry: false }); return <SimpleListPage title={t('correlations')} text={t('correlationsDescription')} query={query} offset={offset} limit={limit} setOffset={setOffset} headers={[t('sourceEvent'), t('targetEvent'), t('type'), t('score'), t('reason')]} rows={query.data?.items.map((item) => [item.source_event_id, item.target_event_id, item.type, `${number(Math.round(item.score * 100))}%`, item.reason]) || []} />; }
export function OutliersPage() { const {t,number,dateTime}=useI18n();const [offset, setOffset] = useState(0); const limit = 20; const query = useQuery({ queryKey: ['outliers', offset], queryFn: () => api.intelligenceOutliers(limit, offset), retry: false }); return <SimpleListPage title={t('outliers')} text={t('outliersDescription')} query={query} offset={offset} limit={limit} setOffset={setOffset} headers={[t('start'), t('end'), t('alerts'), t('score'), t('status')]} rows={query.data?.items.map((item) => [dateTime(item.started_at), dateTime(item.ended_at), number(item.alert_count), number(item.anomaly_score), item.is_outlier ? t('outlier') : t('normal')]) || []} />; }
function SimpleListPage({ title, text, query, offset, limit, setOffset, headers, rows }: { title: string; text: string; query: ReturnType<typeof useQuery<Page<unknown>>>; offset: number; limit: number; setOffset: (v: number) => void; headers: string[]; rows: string[][] }) { const {t}=useI18n();return <section className="page-section intelligence-module"><Heading eyebrow={t('intelligence')} title={title} text={text} /><PageState query={query} empty={t('noData')}><div className="table-shell"><table><thead><tr>{headers.map((item) => <th key={item}>{item}</th>)}</tr></thead><tbody>{rows.map((row, index) => <tr key={index}>{row.map((cell, cellIndex) => <td key={cellIndex}>{cell}</td>)}</tr>)}</tbody></table></div></PageState>{query.data && <Pager total={query.data.total} offset={offset} limit={limit} setOffset={setOffset} />}</section>; }

export function AnalysisPage() { const {t,number}=useI18n();const ml = useQuery({ queryKey: ['ml-status'], queryFn: api.mlStatus, retry: false }); const [offset, setOffset] = useState(0); const limit = 20; const runs = useQuery({ queryKey: ['analysis-runs', offset], queryFn: () => api.analysisRuns(limit, offset), retry: false }); const [selected, setSelected] = useState(''); const detail = useQuery({ queryKey: ['analysis-run', selected], queryFn: () => api.analysisRun(selected), enabled: Boolean(selected), retry: false }); return <section className="page-section analysis-module"><Heading eyebrow={t('analysisEyebrow')} title={t('analysisOperations')} text={t('analysisExecutionModel')} />{ml.isLoading && <LoadingState />}{ml.isError && <ErrorState onRetry={() => void ml.refetch()} />}{ml.data && <div className="metric-grid"><article className="metric-card analysis-accent"><span>{t('analysisBackend')}</span><strong>{ml.data.backend}</strong><small>{ml.data.primary_model}</small></article><article className="metric-card"><span>{t('primaryModel')}</span><strong>{ml.data.primary_loaded ? t('available') : t('unavailableAccess')}</strong></article><article className="metric-card"><span>{t('qualityGates')}</span><strong>{ml.data.quality_gates_passed ? t('successful') : t('incomplete')}</strong></article></div>}<h3 className="subheading">{t('runHistory')}</h3>{runs.isLoading && <LoadingState />}{runs.isError && <ErrorState onRetry={() => void runs.refetch()} />}{runs.data?.items.length === 0 && <EmptyState label={t('noAnalysisRuns')} />}{runs.data && runs.data.items.length > 0 && <><div className="table-shell"><table><thead><tr><th>{t('analysisRun')}</th><th>{t('pipeline')}</th><th>{t('status')}</th><th>{t('processed')}</th><th>{t('duration')}</th></tr></thead><tbody>{runs.data.items.map((run) => <tr key={run.id}><td><button className="button button-quiet" onClick={() => setSelected(run.id)}>{run.id.slice(0, 8)}</button></td><td>{run.pipeline}</td><td><StatusBadge status={run.status} /></td><td>{number(run.processed)} / {number(run.failed)}</td><td>{run.duration_seconds === undefined ? t('inProgress') : t('secondsShort',{value:number(run.duration_seconds)})}</td></tr>)}</tbody></table></div><Pager total={runs.data.total} offset={offset} limit={limit} setOffset={setOffset} /></>}{detail.isLoading && <LoadingState label={t('loadingRunDetails')} />}{detail.isError && <ErrorState onRetry={() => void detail.refetch()} />}{detail.data && <article className="detail-panel"><h3>{t('selectedRunDetails')}</h3><p>{t('runCounters',{collected:number(detail.data.collected),processed:number(detail.data.processed),stored:number(detail.data.stored),failed:number(detail.data.failed)})}</p>{detail.data.error_category && <p>{t('errorCategory')}: {detail.data.error_category}</p>}</article>}</section>; }

export function MISPPage() {
  const {t,number,dateTime}=useI18n();const { user } = useAuth(); const health = useQuery({ queryKey: ['misp-health'], queryFn: api.mispHealth, retry: false }); const history = useQuery({ queryKey: ['misp-deliveries'], queryFn: () => api.mispDeliveries(), retry: false }); const [eventOffset, setEventOffset] = useState(0); const [eventSearch, setEventSearch] = useState(''); const eventLimit = 20; const events = useQuery({ queryKey: ['misp-events', eventOffset, eventSearch], queryFn: () => api.intelligenceEvents(eventLimit, eventOffset, { search: eventSearch.length >= 2 ? eventSearch : '' }), retry: false }); const [eventId, setEventId] = useState(''); const preview = useQuery({ queryKey: ['misp-preview', eventId], queryFn: () => api.mispPreview(eventId), enabled: Boolean(eventId), retry: false }); const send = useMutation({ mutationFn: () => api.mispSend(eventId), onSuccess: () => void history.refetch() });
  function confirmSend() { if (!send.isPending && window.confirm(t('confirmMispSend'))) send.mutate(); }
  return <section className="page-section misp-module"><Heading eyebrow={t('mispEyebrow')} title="MISP" text={t('mispDescription')} />{health.isLoading && <LoadingState />}{health.isError && <ErrorState onRetry={() => void health.refetch()} />}{health.data && <article className="health-card misp-accent"><span>{t('mispHealth')}</span><strong>{!health.data.configured ? t('mispUnconfigured') : health.data.reachable ? t('connected') : t('mispDisconnected')}</strong><StatusBadge status={health.data.reachable ? 'healthy' : health.data.configured ? 'unavailable' : 'disabled'} /></article>}
    <div className="select-block"><label htmlFor="misp-event-search">{t('searchEvents')}</label><input id="misp-event-search" value={eventSearch} onChange={(e) => { setEventSearch(e.target.value); setEventOffset(0); setEventId(''); }} placeholder={t('minimumTwoCharacters')} /><label htmlFor="misp-event-select">{t('event')}</label><select id="misp-event-select" value={eventId} onChange={(e) => setEventId(e.target.value)} disabled={events.isLoading || events.isError}><option value="">{t('chooseEventForPreview')}</option>{events.data?.items.map((event) => <option value={event.id} key={event.id}>{event.title}</option>)}</select></div>{events.isLoading && <LoadingState label={t('loadingEvents')} />}{events.isError && <ErrorState onRetry={() => void events.refetch()} />}{events.data?.items.length === 0 && <EmptyState label={t('noPreviewEvents')} />}{events.data && <Pager total={events.data.total} offset={eventOffset} limit={eventLimit} setOffset={(value) => { setEventOffset(value); setEventId(''); }} />}
    {preview.isLoading && <LoadingState label={t('preparingPreview')} />}{preview.isError && <ErrorState onRetry={() => void preview.refetch()} />}{preview.data && <article className="detail-panel"><h3>{preview.data.title}</h3><div className="integration-facts"><span>{t('willSend')}: <strong>{number(preview.data.included)}</strong></span><span>{t('safelyOmitted')}: <strong>{number(preview.data.omitted)}</strong></span><span>{t('publishing')}: <strong>{t('no')}</strong></span></div>{preview.data.omitted > 0 && <p>{t('omittedBreakdown',{references:number(preview.data.omitted_by_reason.external_reference || 0),invalid:number(preview.data.omitted_by_reason.invalid || 0),nonActionable:number(preview.data.omitted_by_reason.non_actionable || 0),unsupported:number(preview.data.omitted_by_reason.unsupported || 0)})}</p>}{preview.data.attributes.length ? <ul className="misp-attributes">{preview.data.attributes.map((item, index) => <li key={`${item.type}-${index}`}><strong>{item.type}</strong>: <code dir="ltr">{item.value}</code> <small>({item.category} · {t('idsLabel')}: {item.to_ids ? t('yes') : t('no')})</small></li>)}</ul> : <p>{t('noTransferableAttributes')}</p>}{user?.role === 'admin' && <button className="button button-primary" disabled={send.isPending || !preview.data.configured || preview.data.included === 0} onClick={confirmSend}>{send.isPending ? t('sendingAndVerifying') : t('sendToMisp')}</button>}</article>}
    {send.isSuccess && <div className="pull-result" role="status">{t('mispSendSuccess',{requested:number(send.data.attributes_requested),added:number(send.data.attributes_added),verified:number(send.data.attributes_verified),published:send.data.published?t('yes'):t('no')})}</div>}{send.isError && <div className="form-error" role="alert">{send.error instanceof ApiError && send.error.status === 403 ? t('mispAdminOnly') : t('mispSafeFailure')}</div>}
    <section className="detail-list"><h3>{t('mispDeliveryHistory')}</h3>{history.isLoading && <LoadingState label={t('loadingHistory')} />}{history.isError && <ErrorState onRetry={() => void history.refetch()} />}{history.data?.items.length === 0 && <p>{t('noMispDeliveries')}</p>}{history.data && history.data.items.length > 0 && <div className="table-shell"><table><thead><tr><th>{t('time')}</th><th>{t('event')}</th><th>{t('user')}</th><th>{t('requested')}</th><th>{t('added')}</th><th>{t('verified')}</th><th>{t('publishing')}</th></tr></thead><tbody>{history.data.items.map((item) => <tr key={item.id}><td>{dateTime(item.created_at)}</td><td>{item.event_id ? <Link to={`/intelligence/events/${item.event_id}`}>{item.event_id.slice(0, 12)}</Link> : t('notAvailable')}</td><td>{item.username || t('notAvailable')}</td><td>{item.attributes_requested === undefined ? t('legacy') : number(item.attributes_requested)}</td><td>{item.attributes_added === undefined ? t('legacy') : number(item.attributes_added)}</td><td>{item.attributes_verified === undefined ? t('legacy') : number(item.attributes_verified)}</td><td>{item.published === undefined ? t('notRecorded') : item.published ? t('yes') : t('no')}</td></tr>)}</tbody></table></div>}</section>
  </section>;
}
