import { useState } from 'react';
import { useMutation, useQuery } from '@tanstack/react-query';
import { Link, useParams } from 'react-router-dom';
import { api, ApiError, type Page } from '../api/client';
import { useAuth } from '../auth/AuthContext';
import { EmptyState, ErrorState, LoadingState } from '../components/States';
import { StatusBadge } from '../components/StatusBadge';

const time = (value?: string) => value ? new Intl.DateTimeFormat('ar', { dateStyle: 'medium', timeStyle: 'short' }).format(new Date(value)) : 'غير متوفر';
function PageState({ query, empty, children }: { query: { isLoading: boolean; isError: boolean; refetch: () => unknown; data?: Page<unknown> }; empty: string; children: React.ReactNode }) { if (query.isLoading) return <LoadingState />; if (query.isError) return <ErrorState onRetry={() => void query.refetch()} />; if (query.data?.items.length === 0) return <EmptyState label={empty} />; return <>{children}</>; }
function Pager({ total, offset, limit, setOffset }: { total: number; offset: number; limit: number; setOffset: (value: number) => void }) { return <div className="pagination"><button className="button button-secondary" disabled={!offset} onClick={() => setOffset(Math.max(0, offset - limit))}>السابق</button><span>{total ? `${offset + 1}–${Math.min(total, offset + limit)} من ${total}` : '0'}</span><button className="button button-secondary" disabled={offset + limit >= total} onClick={() => setOffset(offset + limit)}>التالي</button></div>; }
function Heading({ eyebrow, title, text }: { eyebrow: string; title: string; text: string }) { return <div className="section-heading"><div><span className="eyebrow">{eyebrow}</span><h2>{title}</h2><p>{text}</p></div></div>; }

export function IntelligenceOverview() {
  const summary = useQuery({ queryKey: ['dashboard-summary'], queryFn: api.dashboardSummary, retry: false });
  return <section className="page-section intelligence-module"><Heading eyebrow="الاستخبارات والتحليل / 01" title="نظرة عامة" text="لقطة حالية من السجلات المركزية دون اتجاهات زمنية مصطنعة." />{summary.isLoading && <LoadingState />}{summary.isError && <ErrorState onRetry={() => void summary.refetch()} />}{summary.data && <><div className="metric-grid">{[['الأحداث', summary.data.events], ['كل القيم المرصودة', summary.data.observables], ['مؤشرات مثبتة', summary.data.indicators], ['الارتباطات', summary.data.correlations], ['القيم الشاذة', summary.data.outliers]].map(([label, value]) => <article className="metric-card intel-accent" key={label}><span>{label}</span><strong>{Number(value).toLocaleString('ar')}</strong></article>)}</div><div className="distribution-grid"><Distribution title="الشدة" values={summary.data.by_severity} /><Distribution title="خط المعالجة" values={summary.data.by_pipeline} /></div></>}</section>;
}
function Distribution({ title, values }: { title: string; values: Record<string, number> }) { const entries = Object.entries(values); const max = Math.max(0, ...entries.map(([, value]) => value)); return <article className="distribution-card"><h3>{title}</h3>{!entries.length ? <p>لا توجد بيانات</p> : entries.map(([label, value]) => <div className="bar-row" key={label}><div><span>{label}</span><strong>{value} سجل</strong></div><span className="bar-track" role="img" aria-label={`${label}: ${value}`}><span className="bar-fill intel-fill" style={{ width: `${max ? value / max * 100 : 0}%` }} /></span></div>)}</article>; }

export function EventsPage() {
  const [offset, setOffset] = useState(0); const [severity, setSeverity] = useState(''); const [pipeline, setPipeline] = useState(''); const [search, setSearch] = useState(''); const limit = 20;
  const query = useQuery({ queryKey: ['intel-events', offset, severity, pipeline, search], queryFn: () => api.intelligenceEvents(limit, offset, { severity, source_pipeline: pipeline, search: search.length >= 2 ? search : '' }), retry: false });
  return <section className="page-section intelligence-module"><Heading eyebrow="الاستخبارات" title="الأحداث" text="أحداث CTI المعالجة مع ملخصات آمنة وعقود عرض محدودة." /><div className="filters"><input aria-label="بحث الأحداث" placeholder="بحث في العنوان" value={search} onChange={(e) => { setSearch(e.target.value); setOffset(0); }} /><select aria-label="خط المعالجة" value={pipeline} onChange={(e) => { setPipeline(e.target.value); setOffset(0); }}><option value="">كل الخطوط</option><option value="external">خارجي</option><option value="internal">داخلي</option></select><select aria-label="الشدة" value={severity} onChange={(e) => { setSeverity(e.target.value); setOffset(0); }}><option value="">كل الشدات</option><option value="critical">حرجة</option><option value="high">عالية</option><option value="medium">متوسطة</option><option value="low">منخفضة</option></select></div><PageState query={query} empty="لا توجد أحداث"><EventTable items={query.data?.items || []} /></PageState>{query.data && <Pager total={query.data.total} offset={offset} limit={limit} setOffset={setOffset} />}</section>;
}
function EventTable({ items }: { items: Awaited<ReturnType<typeof api.intelligenceEvents>>['items'] }) { return <div className="table-shell"><table><thead><tr><th>الحدث</th><th>المصدر</th><th>الشدة</th><th>الحالة</th><th>الوقت</th></tr></thead><tbody>{items.map((item) => <tr key={item.id}><td><Link to={`/intelligence/events/${item.id}`}><strong>{item.title}</strong></Link><small>{item.summary}</small></td><td>{item.source_type}<small>{item.source_pipeline}</small></td><td><StatusBadge status={item.severity || 'unknown'} /></td><td>{item.processing_status}</td><td>{time(item.first_seen || item.created_at)}</td></tr>)}</tbody></table></div>; }

export function EventDetailPage() { const { eventId = '' } = useParams(); const query = useQuery({ queryKey: ['intel-event', eventId], queryFn: () => api.intelligenceEvent(eventId), retry: false }); const attack = useQuery({ queryKey: ['attack-event', eventId], queryFn: () => api.attackMapping(eventId), enabled: Boolean(eventId), retry: false }); const stix = useMutation({ mutationFn: () => api.stixBundle(eventId), onSuccess: (bundle) => { const url = URL.createObjectURL(new Blob([JSON.stringify(bundle, null, 2)], { type: 'application/json' })); const link = document.createElement('a'); link.href = url; link.download = `cti-${eventId}.stix.json`; link.click(); URL.revokeObjectURL(url); } }); return <section className="page-section intelligence-module"><Heading eyebrow="تفاصيل الحدث" title={query.data?.title || 'الحدث'} text="تفاصيل تحليلية من الإسقاط المركزي الآمن." />{query.isLoading && <LoadingState />}{query.isError && <ErrorState onRetry={() => void query.refetch()} />}{query.data && <><article className="detail-panel"><p>{query.data.summary}</p><div className="integration-facts"><span>الشدة: <strong>{query.data.severity || 'غير محددة'}</strong></span><span>المخاطر: <strong>{query.data.risk_score}</strong></span><span>الثقة: <strong>{Math.round(query.data.confidence * 100)}%</strong></span></div><button className="button button-secondary" disabled={stix.isPending} onClick={() => stix.mutate()}>{stix.isPending ? 'جار تجهيز STIX...' : 'تنزيل STIX'}</button>{stix.isSuccess && <span role="status" className="copy-feedback">تم تجهيز ملف STIX.</span>}{stix.isError && <div className="form-error" role="alert">تعذر تجهيز STIX. أعد المحاولة.</div>}</article><DetailList title="القيم المرصودة والتقييم" items={query.data.indicators.map((item) => `${roleLabel(item.semantic_role)} · ${assessmentLabel(item.assessment)} · ${item.type}: ${item.value}`)} /><DetailList title="الكيانات" items={query.data.entities.map((item) => `${item.type}: ${item.value}`)} /><DetailList title="العلاقات" items={query.data.relationships.map((item) => `${item.subject} — ${item.relation} — ${item.object}`)} />{attack.data && <AttackResults data={attack.data} />}{attack.isError && <div className="notice"><span className="notice-mark">i</span><div><strong>تعذر تحليل ATT&amp;CK لهذا الحدث</strong><p>لم يؤثر ذلك في بقية تفاصيل الحدث.</p></div></div>}</>}</section>; }
function DetailList({ title, items }: { title: string; items: string[] }) { return <section className="detail-list"><h3>{title}</h3>{items.length ? <ul>{items.map((item, index) => <li key={`${index}-${item}`}>{item}</li>)}</ul> : <p>لا توجد بيانات</p>}</section>; }

const roleLabel = (value: string) => ({ external_reference: 'مرجع خارجي', vulnerability: 'ثغرة', observable: 'قيمة مرصودة', indicator: 'مؤشر تهديد' }[value] || value);
const assessmentLabel = (value: string) => ({ reference: 'مرجع فقط', non_actionable: 'غير قابل للتنفيذ', unknown: 'غير محسوم', suspicious: 'مشبوه', malicious: 'خبيث' }[value] || value);
const reasonLabel = (value: string) => ({ embedded_in_url: 'جزء من رابط', reference_host: 'موقع مرجعي', vulnerability_id: 'معرّف ثغرة', non_global_ip: 'عنوان غير عام', non_global_url_host: 'رابط محلي أو غير عام', reserved_domain: 'نطاق محجوز', locally_administered_mac: 'MAC محلي', needs_enrichment: 'يحتاج إثراء', enrichment_verdict: 'حكم إثراء', unsupported_type: 'نوع غير مدعوم' }[value] || value);

export function IndicatorsPage() {
  const [offset, setOffset] = useState(0); const [type, setType] = useState(''); const [role, setRole] = useState(''); const [assessment, setAssessment] = useState(''); const [validation, setValidation] = useState(''); const [search, setSearch] = useState(''); const [copied, setCopied] = useState(''); const limit = 20;
  const summary = useQuery({ queryKey: ['indicator-summary'], queryFn: api.intelligenceIndicatorSummary, retry: false });
  const filters = { type, semantic_role: role, assessment, validation_status: validation, search: search.length >= 2 ? search : '' };
  const query = useQuery({ queryKey: ['indicators', offset, filters], queryFn: () => api.intelligenceIndicators(limit, offset, filters), retry: false });
  async function copy(id: string, value: string) { await navigator.clipboard.writeText(value); setCopied(id); }
  return <section className="page-section intelligence-module"><Heading eyebrow="الاستخبارات" title="القيم المرصودة والمؤشرات" text="القيمة المستخرجة ليست خبيثة تلقائيًا. تعرض الصفحة الدور الدلالي، صلاحية الصيغة، والحكم المدعوم بالأدلة كلًّا على حدة." />
    {summary.data && <div className="metric-grid compact-metrics">{[['كل القيم', summary.data.total], ['قيم مرصودة', summary.data.by_role.observable || 0], ['مراجع خارجية', summary.data.by_role.external_reference || 0], ['ثغرات', summary.data.by_role.vulnerability || 0], ['مؤشرات مثبتة', summary.data.by_role.indicator || 0]].map(([label, value]) => <article className="metric-card intel-accent" key={label}><span>{label}</span><strong>{Number(value).toLocaleString('ar')}</strong></article>)}</div>}
    <div className="notice indicator-notice"><span className="notice-mark">i</span><div><strong>100% تعني ثقة الاستخراج، وليست نسبة الخبث</strong><p>لا تُرفع القيمة إلى «مؤشر تهديد» ولا تُفعل في IDS/MISP إلا عند وجود حكم إثراء صريح. «غير محسوم» لا تعني آمنًا.</p></div></div>
    <div className="filters"><input aria-label="بحث المؤشرات" value={search} onChange={(e) => { setSearch(e.target.value); setOffset(0); }} placeholder="بحث في القيمة" /><input aria-label="نوع المؤشر" value={type} onChange={(e) => { setType(e.target.value); setOffset(0); }} placeholder="النوع، مثل url" /><select aria-label="الدور الدلالي" value={role} onChange={(e) => { setRole(e.target.value); setOffset(0); }}><option value="">كل الأدوار</option><option value="observable">قيمة مرصودة</option><option value="external_reference">مرجع خارجي</option><option value="vulnerability">ثغرة</option><option value="indicator">مؤشر تهديد</option></select><select aria-label="التقييم" value={assessment} onChange={(e) => { setAssessment(e.target.value); setOffset(0); }}><option value="">كل التقييمات</option><option value="unknown">غير محسوم</option><option value="reference">مرجع فقط</option><option value="non_actionable">غير قابل للتنفيذ</option><option value="suspicious">مشبوه</option><option value="malicious">خبيث</option></select><select aria-label="صلاحية القيمة" value={validation} onChange={(e) => { setValidation(e.target.value); setOffset(0); }}><option value="">كل الصيغ</option><option value="valid">صالحة</option><option value="invalid">غير صالحة</option></select></div>
    <PageState query={query} empty="لا توجد قيم مطابقة"><div className="table-shell"><table className="indicator-table"><thead><tr><th>النوع</th><th>القيمة</th><th>الدور والتقييم</th><th>ثقة الاستخراج</th><th>الأدلة</th><th>المصدر</th><th>إجراء</th></tr></thead><tbody>{query.data?.items.map((item) => <tr key={item.id}><td>{item.type}</td><td><Link to={`/intelligence/events/${item.event_id}`}><code className="indicator-value" dir="ltr">{item.value}</code></Link></td><td><StatusBadge status={item.actionable ? 'warning' : item.validation_status === 'invalid' ? 'unavailable' : 'healthy'} /><strong className="assessment-title">{roleLabel(item.semantic_role)}</strong><small>{assessmentLabel(item.assessment)} · {reasonLabel(item.reason_code)}</small></td><td>{Math.round(item.confidence * 100)}%<small>استخراج فقط</small></td><td>{item.evidence_count ? item.evidence_providers.join(', ') : 'لا يوجد'}<small>{Math.round(item.assessment_confidence * 100)}% ثقة التقييم</small></td><td>{item.source_pipeline}</td><td><button className="button button-quiet" onClick={() => void copy(item.id, item.value)}>نسخ</button>{copied === item.id && <span role="status">تم النسخ</span>}</td></tr>)}</tbody></table></div></PageState>{query.data && <Pager total={query.data.total} offset={offset} limit={limit} setOffset={setOffset} />}</section>;
}

function AttackResults({ data }: { data: Awaited<ReturnType<typeof api.attackMapping>> }) { return <section className="detail-list attack-results"><div className="attack-heading"><h3>MITRE ATT&amp;CK</h3><a href={data.official_dataset_url} target="_blank" rel="noreferrer">{data.catalog_version}</a></div>{data.techniques.length ? <div className="attack-grid">{data.techniques.map((item) => <article key={item.technique_id}><a href={item.url} target="_blank" rel="noreferrer"><strong dir="ltr">{item.technique_id}</strong> · {item.name}</a><span>{item.tactic} · {item.mapping_source === 'explicit_id' ? 'معرّف صريح' : 'مرشح آلي للمراجعة'} · {Math.round(item.confidence * 100)}%</span><p>{item.evidence}</p></article>)}</div> : <p>لم تُكتشف تقنية بدليل كافٍ في هذا الحدث.</p>}</section>; }

export function AttackPage() { const [eventOffset, setEventOffset] = useState(0); const [eventSearch, setEventSearch] = useState(''); const [eventId, setEventId] = useState(''); const eventLimit = 20; const events = useQuery({ queryKey: ['attack-events', eventOffset, eventSearch], queryFn: () => api.intelligenceEvents(eventLimit, eventOffset, { search: eventSearch.length >= 2 ? eventSearch : '' }), retry: false }); const mapping = useQuery({ queryKey: ['attack-mapping', eventId], queryFn: () => api.attackMapping(eventId), enabled: Boolean(eventId), retry: false }); return <section className="page-section intelligence-module"><Heading eyebrow="السلوك / ATT&CK" title="MITRE ATT&CK" text="ربط محافظ لسلوك الحدث: المعرّفات الصريحة مؤكدة، والقواعد النصية تظهر كمرشحات تحتاج مراجعة محلل." /><div className="select-block"><label htmlFor="attack-event-search">بحث الأحداث</label><input id="attack-event-search" value={eventSearch} onChange={(e) => { setEventSearch(e.target.value); setEventOffset(0); setEventId(''); }} placeholder="اكتب حرفين على الأقل" /><label htmlFor="attack-event-select">الحدث</label><select id="attack-event-select" value={eventId} onChange={(e) => setEventId(e.target.value)}><option value="">اختر حدثًا للتحليل</option>{events.data?.items.map((event) => <option value={event.id} key={event.id}>{event.title}</option>)}</select></div>{events.isLoading && <LoadingState label="جار تحميل الأحداث..." />}{events.isError && <ErrorState onRetry={() => void events.refetch()} />}{events.data && <Pager total={events.data.total} offset={eventOffset} limit={eventLimit} setOffset={(value) => { setEventOffset(value); setEventId(''); }} />}{mapping.isLoading && <LoadingState label="جار ربط ATT&CK..." />}{mapping.isError && <ErrorState onRetry={() => void mapping.refetch()} />}{mapping.data && <AttackResults data={mapping.data} />}</section>; }

export function CorrelationsPage() { const [offset, setOffset] = useState(0); const limit = 20; const query = useQuery({ queryKey: ['correlations', offset], queryFn: () => api.intelligenceCorrelations(limit, offset), retry: false }); return <SimpleListPage title="الارتباطات" text="علاقات مخزنة فعلية بين أحداث المصدر والهدف." query={query} offset={offset} limit={limit} setOffset={setOffset} headers={['المصدر', 'الهدف', 'النوع', 'الدرجة', 'السبب']} rows={query.data?.items.map((item) => [item.source_event_id, item.target_event_id, item.type, `${Math.round(item.score * 100)}%`, item.reason]) || []} />; }
export function OutliersPage() { const [offset, setOffset] = useState(0); const limit = 20; const query = useQuery({ queryKey: ['outliers', offset], queryFn: () => api.intelligenceOutliers(limit, offset), retry: false }); return <SimpleListPage title="القيم الشاذة" text="نتائج كشف الشذوذ دون عناوين IP أو خصائص جلسة خام." query={query} offset={offset} limit={limit} setOffset={setOffset} headers={['البداية', 'النهاية', 'التنبيهات', 'الدرجة', 'الحالة']} rows={query.data?.items.map((item) => [time(item.started_at), time(item.ended_at), String(item.alert_count), item.anomaly_score.toFixed(3), item.is_outlier ? 'شاذ' : 'طبيعي']) || []} />; }
function SimpleListPage({ title, text, query, offset, limit, setOffset, headers, rows }: { title: string; text: string; query: ReturnType<typeof useQuery<Page<unknown>>>; offset: number; limit: number; setOffset: (v: number) => void; headers: string[]; rows: string[][] }) { return <section className="page-section intelligence-module"><Heading eyebrow="الاستخبارات" title={title} text={text} /><PageState query={query} empty="لا توجد بيانات"><div className="table-shell"><table><thead><tr>{headers.map((item) => <th key={item}>{item}</th>)}</tr></thead><tbody>{rows.map((row, index) => <tr key={index}>{row.map((cell, cellIndex) => <td key={cellIndex}>{cell}</td>)}</tr>)}</tbody></table></div></PageState>{query.data && <Pager total={query.data.total} offset={offset} limit={limit} setOffset={setOffset} />}</section>; }

export function AnalysisPage() { const ml = useQuery({ queryKey: ['ml-status'], queryFn: api.mlStatus, retry: false }); const [offset, setOffset] = useState(0); const limit = 20; const runs = useQuery({ queryKey: ['analysis-runs', offset], queryFn: () => api.analysisRuns(limit, offset), retry: false }); const [selected, setSelected] = useState(''); const detail = useQuery({ queryKey: ['analysis-run', selected], queryFn: () => api.analysisRun(selected), enabled: Boolean(selected), retry: false }); return <section className="page-section analysis-module"><Heading eyebrow="التحليل / ML" title="عمليات التحليل" text="يعمل BERT/NER داخل Central Backend مباشرة؛ لا توجد قائمة انتظار أو خدمة عامل مستقلة." />{ml.isLoading && <LoadingState />}{ml.isError && <ErrorState onRetry={() => void ml.refetch()} />}{ml.data && <div className="metric-grid"><article className="metric-card analysis-accent"><span>Backend التحليل</span><strong>{ml.data.backend}</strong><small>{ml.data.primary_model}</small></article><article className="metric-card"><span>النموذج الأساسي</span><strong>{ml.data.primary_loaded ? 'متاح' : 'غير متاح'}</strong></article><article className="metric-card"><span>بوابات الجودة</span><strong>{ml.data.quality_gates_passed ? 'ناجحة' : 'غير مكتملة'}</strong></article></div>}<h3 className="subheading">سجل التشغيلات</h3>{runs.isLoading && <LoadingState />}{runs.isError && <ErrorState onRetry={() => void runs.refetch()} />}{runs.data?.items.length === 0 && <EmptyState label="لا توجد تشغيلات تحليل" />}{runs.data && runs.data.items.length > 0 && <><div className="table-shell"><table><thead><tr><th>التشغيل</th><th>الخط</th><th>الحالة</th><th>المعالجة</th><th>المدة</th></tr></thead><tbody>{runs.data.items.map((run) => <tr key={run.id}><td><button className="button button-quiet" onClick={() => setSelected(run.id)}>{run.id.slice(0, 8)}</button></td><td>{run.pipeline}</td><td><StatusBadge status={run.status} /></td><td>{run.processed} / {run.failed}</td><td>{run.duration_seconds === undefined ? 'قيد التشغيل' : `${run.duration_seconds.toFixed(1)} ث`}</td></tr>)}</tbody></table></div><Pager total={runs.data.total} offset={offset} limit={limit} setOffset={setOffset} /></>}{detail.isLoading && <LoadingState label="جار تحميل تفاصيل التشغيل..." />}{detail.isError && <ErrorState onRetry={() => void detail.refetch()} />}{detail.data && <article className="detail-panel"><h3>تفاصيل التشغيل المحدد</h3><p>جُمعت {detail.data.collected}، عولجت {detail.data.processed}، خُزنت {detail.data.stored}، وفشلت {detail.data.failed}.</p>{detail.data.error_category && <p>فئة الخطأ: {detail.data.error_category}</p>}</article>}</section>; }

export function MISPPage() {
  const { user } = useAuth(); const health = useQuery({ queryKey: ['misp-health'], queryFn: api.mispHealth, retry: false }); const history = useQuery({ queryKey: ['misp-deliveries'], queryFn: () => api.mispDeliveries(), retry: false }); const [eventOffset, setEventOffset] = useState(0); const [eventSearch, setEventSearch] = useState(''); const eventLimit = 20; const events = useQuery({ queryKey: ['misp-events', eventOffset, eventSearch], queryFn: () => api.intelligenceEvents(eventLimit, eventOffset, { search: eventSearch.length >= 2 ? eventSearch : '' }), retry: false }); const [eventId, setEventId] = useState(''); const preview = useQuery({ queryKey: ['misp-preview', eventId], queryFn: () => api.mispPreview(eventId), enabled: Boolean(eventId), retry: false }); const send = useMutation({ mutationFn: () => api.mispSend(eventId), onSuccess: () => void history.refetch() });
  function confirmSend() { if (!send.isPending && window.confirm('هل تريد إرسال القيم التي اجتازت التقييم إلى MISP؟ لن يُنشر الحدث تلقائيًا ولن تُفعّل IDS للقيم غير المحسومة.')) send.mutate(); }
  return <section className="page-section misp-module"><Heading eyebrow="المشاركة / MISP" title="MISP" text="اتصال خاص بالـVPS، معاينة مفلترة، إرسال غير منشور، ثم تحقق من السمات وسجل تدقيق." />{health.isLoading && <LoadingState />}{health.isError && <ErrorState onRetry={() => void health.refetch()} />}{health.data && <article className="health-card misp-accent"><span>حالة MISP</span><strong>{!health.data.configured ? 'غير مهيأ' : health.data.reachable ? 'متصل' : 'غير متصل'}</strong><StatusBadge status={health.data.reachable ? 'healthy' : health.data.configured ? 'unavailable' : 'disabled'} /></article>}
    <div className="select-block"><label htmlFor="misp-event-search">بحث الأحداث</label><input id="misp-event-search" value={eventSearch} onChange={(e) => { setEventSearch(e.target.value); setEventOffset(0); setEventId(''); }} placeholder="اكتب حرفين على الأقل" /><label htmlFor="misp-event-select">الحدث</label><select id="misp-event-select" value={eventId} onChange={(e) => setEventId(e.target.value)} disabled={events.isLoading || events.isError}><option value="">اختر حدثًا للمعاينة</option>{events.data?.items.map((event) => <option value={event.id} key={event.id}>{event.title}</option>)}</select></div>{events.isLoading && <LoadingState label="جار تحميل الأحداث..." />}{events.isError && <ErrorState onRetry={() => void events.refetch()} />}{events.data?.items.length === 0 && <EmptyState label="لا توجد أحداث قابلة للمعاينة" />}{events.data && <Pager total={events.data.total} offset={eventOffset} limit={eventLimit} setOffset={(value) => { setEventOffset(value); setEventId(''); }} />}
    {preview.isLoading && <LoadingState label="جار إعداد المعاينة..." />}{preview.isError && <ErrorState onRetry={() => void preview.refetch()} />}{preview.data && <article className="detail-panel"><h3>{preview.data.title}</h3><div className="integration-facts"><span>سيُرسل: <strong>{preview.data.included}</strong></span><span>مستبعد بأمان: <strong>{preview.data.omitted}</strong></span><span>النشر: <strong>لا</strong></span></div>{preview.data.omitted > 0 && <p>المستبعد: مراجع {preview.data.omitted_by_reason.external_reference || 0} · غير صالح {preview.data.omitted_by_reason.invalid || 0} · غير قابل للتنفيذ {preview.data.omitted_by_reason.non_actionable || 0} · غير مدعوم {preview.data.omitted_by_reason.unsupported || 0}</p>}{preview.data.attributes.length ? <ul className="misp-attributes">{preview.data.attributes.map((item, index) => <li key={`${item.type}-${index}`}><strong>{item.type}</strong>: <code dir="ltr">{item.value}</code> <small>({item.category} · IDS: {item.to_ids ? 'نعم' : 'لا'})</small></li>)}</ul> : <p>لا توجد سمات اجتازت التقييم وقابلة للنقل.</p>}{user?.role === 'admin' && <button className="button button-primary" disabled={send.isPending || !preview.data.configured || preview.data.included === 0} onClick={confirmSend}>{send.isPending ? 'جار الإرسال والتحقق...' : 'إرسال إلى MISP'}</button>}</article>}
    {send.isSuccess && <div className="pull-result" role="status">طُلبت {send.data.attributes_requested}، أضيفت {send.data.attributes_added}، وتحققنا من {send.data.attributes_verified}. النشر: {send.data.published ? 'نعم' : 'لا'}.</div>}{send.isError && <div className="form-error" role="alert">{send.error instanceof ApiError && send.error.status === 403 ? 'الإرسال متاح للمسؤول فقط.' : 'تعذر إرسال الحدث بأمان.'}</div>}
    <section className="detail-list"><h3>سجل تسليم MISP</h3>{history.isLoading && <LoadingState label="جار تحميل السجل..." />}{history.isError && <ErrorState onRetry={() => void history.refetch()} />}{history.data?.items.length === 0 && <p>لم تُسجل عمليات إرسال بعد.</p>}{history.data && history.data.items.length > 0 && <div className="table-shell"><table><thead><tr><th>الوقت</th><th>الحدث</th><th>المستخدم</th><th>المطلوب</th><th>المضاف</th><th>المتحقق</th><th>النشر</th></tr></thead><tbody>{history.data.items.map((item) => <tr key={item.id}><td>{time(item.created_at)}</td><td>{item.event_id ? <Link to={`/intelligence/events/${item.event_id}`}>{item.event_id.slice(0, 12)}</Link> : 'غير متوفر'}</td><td>{item.username || 'غير متوفر'}</td><td>{item.attributes_requested ?? 'قديم'}</td><td>{item.attributes_added ?? 'قديم'}</td><td>{item.attributes_verified ?? 'قديم'}</td><td>{item.published === undefined ? 'غير مسجل' : item.published ? 'نعم' : 'لا'}</td></tr>)}</tbody></table></div>}</section>
  </section>;
}
