import {useEffect,useMemo,useRef,useState} from 'react';
import {useMutation,useQuery,useQueryClient} from '@tanstack/react-query';
import {api,ApiError,type ReviewRecord} from '../api/client';
import {EmptyState,ErrorState,LoadingState} from '../components/States';
import {useI18n} from '../i18n/I18nContext';
import {useAuth} from '../auth/AuthContext';
import {externalQueryKeys} from '../api/externalQueryKeys';

export function Reviews(){
  const {t,number,dateTime}=useI18n(),{can}=useAuth(),client=useQueryClient();
  const [search,setSearch]=useState(''),[type,setType]=useState('all');
  const [reason,setReason]=useState<'not_relevant'|'duplicate'|'privacy_risk'|'low_quality'>('not_relevant');
  const [message,setMessage]=useState('');
  const [records,setRecords]=useState<ReviewRecord[]>([]);
  const [pageMeta,setPageMeta]=useState({total:0,offset:0,malformed:0});
  const controller=useRef<AbortController|undefined>(undefined);
  const query=useQuery({queryKey:externalQueryKeys.reviews(search,type),queryFn:({signal})=>api.latestExternalReviews(20,0,signal),retry:false});
  const more=useMutation({mutationFn:({offset,signal}:{offset:number;signal:AbortSignal})=>api.latestExternalReviews(20,offset,signal),onSuccess:value=>{setRecords(current=>{const seen=new Set(current.map(item=>`${item.record_id}:${item.content_sha256}`));return [...current,...value.records.filter(item=>!seen.has(`${item.record_id}:${item.content_sha256}`))]});setPageMeta(current=>({total:value.total,offset:value.offset+value.records.length,malformed:current.malformed+value.malformed_records}))}});
  const decision=useMutation({mutationFn:({record,action,selectedReason,signal}:{record:ReviewRecord;action:'approved'|'rejected';selectedReason:typeof reason;signal:AbortSignal})=>api.decideExternalReview(record,action,action==='rejected'?selectedReason:undefined,signal),onSuccess:(value)=>{setMessage(value.decision==='approved'?t('reviewApproved'):t('reviewRejected'));setRecords([]);void client.invalidateQueries({queryKey:['external','reviews']});void client.invalidateQueries({queryKey:externalQueryKeys.reviewLifecycle()});if(value.decision==='approved')void client.invalidateQueries({queryKey:['external','accepted-records']})}});
  useEffect(()=>()=>controller.current?.abort(),[]);
  useEffect(()=>{if(query.data){setRecords(query.data.records);setPageMeta({total:query.data.total,offset:query.data.records.length,malformed:query.data.malformed_records})}},[query.data]);
  const types=[...new Set(records.map(record=>record.source_type).filter(Boolean))] as string[];
  const filtered=useMemo(()=>records.filter(record=>(type==='all'||record.source_type===type)&&[record.title,record.source_type,record.source,record.category,record.review_reason,...record.review_reasons].some(value=>value?.toLocaleLowerCase().includes(search.toLocaleLowerCase()))),[records,search,type]);
  const retry=()=>void query.refetch();
  const loadMore=()=>{if(more.isPending||pageMeta.offset>=pageMeta.total)return;controller.current?.abort();controller.current=new AbortController();more.mutate({offset:pageMeta.offset,signal:controller.current.signal})};
  const decide=(record:ReviewRecord,action:'approved'|'rejected')=>{if(decision.isPending||!window.confirm(action==='approved'?t('confirmReviewApprove'):t('confirmReviewReject')))return;controller.current?.abort();controller.current=new AbortController();setMessage('');decision.reset();decision.mutate({record,action,selectedReason:reason,signal:controller.current.signal})};
  return <section className="page-section"><div className="section-heading"><div><span className="eyebrow">{t('reviews')} / 06</span><h2>{t('latestReviews')}</h2><p>{t('reviewsDescription')}</p></div><span className="count-label">{t('recordsCount',{count:number(filtered.length)})}</span></div>
    <div className="filters"><label className="search-wrap"><span className="sr-only">{t('search')}</span><input value={search} onChange={event=>setSearch(event.target.value)} placeholder={t('safeDataSearch')}/></label><select aria-label={t('filterSourceType')} value={type} onChange={event=>setType(event.target.value)}><option value="all">{t('allTypes')}</option>{types.map(value=><option key={value}>{value}</option>)}</select>{can('analyst')&&<select aria-label={t('rejectReason')} value={reason} onChange={event=>setReason(event.target.value as typeof reason)}><option value="not_relevant">{t('notRelevant')}</option><option value="duplicate">{t('duplicate')}</option><option value="privacy_risk">{t('privacy')}</option><option value="low_quality">{t('lowQuality')}</option></select>}</div>
    {query.isLoading&&<LoadingState label={t('loadingReviews')}/>} {query.isError&&query.data&&<div className="state-panel" role="status"><strong>{t('staleDataWarning')}</strong><button className="button button-secondary" onClick={retry}>{t('retry')}</button></div>} {query.isError&&!query.data&&(query.error instanceof ApiError&&query.error.status===404&&query.error.code==='review_not_found'?<EmptyState label={t('noReviews')}/>:query.error instanceof ApiError&&query.error.status===401?<div className="state-panel error-panel" role="alert">{t('sessionExpired')}</div>:query.error instanceof TypeError||query.error instanceof ApiError&&(query.error.status===408||query.error.status===503)?<div className="state-panel error-panel" role="alert"><strong>{t('reviewsUnavailable')}</strong><button className="button button-secondary" onClick={retry}>{t('retry')}</button></div>:<ErrorState onRetry={retry}/>)}
    {decision.isError&&(decision.error instanceof ApiError&&decision.error.status===409?<div className="state-panel error-panel" role="alert">{t('reviewConflict')}</div>:<ErrorState onRetry={()=>decision.reset()}/>)}
    {message&&<div className="job-panel" role="status">{message}</div>}
    {!query.isLoading&&records.length===0&&(!query.isError||Boolean(query.data))&&<EmptyState label={t('noReviews')}/>}
    {records.length>0&&filtered.length===0&&<EmptyState label={t('noMatches')}/>}
    {filtered.length>0&&<div className="card-list">{filtered.map(record=><article className="review-card" key={record.record_id}><div><strong>{record.title||t('untitled')}</strong><span>{record.source}</span></div>{record.status!=='pending'&&<div className="safe-label" role="status">{t(record.status==='processing_failed'?'reviewProcessingFailed':'reviewProcessing')}</div>}{record.summary&&<p>{record.summary}</p>}<p>{record.excerpt}</p><dl><div><dt>{t('sourceType')}</dt><dd>{record.source_type||t('notAvailable')}</dd></div><div><dt>{t('reviewReason')}</dt><dd>{record.review_reasons.join(', ')||record.review_reason}</dd></div><div><dt>{t('classification')}</dt><dd>{record.classification_label||t('unclassified')}</dd></div><div><dt>{t('privacy')}</dt><dd>{record.privacy_status||t('notAvailable')}</dd></div><div><dt>{t('collectedAt')}</dt><dd>{record.collected_at?dateTime(record.collected_at):t('notAvailable')}</dd></div>{record.published&&<div><dt>{t('publishedAt')}</dt><dd>{dateTime(record.published)}</dd></div>}</dl>{can('analyst')&&<details><summary>{t('technicalDetails')}</summary><code dir="ltr">{record.content_sha256.slice(7,19)}… · {record.review_version}</code></details>}{can('analyst')&&record.status==='pending'&&<div><button disabled={decision.isPending} onClick={()=>decide(record,'approved')}>{t('approveSave')}</button><button disabled={decision.isPending} onClick={()=>decide(record,'rejected')}>{t('reject')}</button></div>}</article>)}</div>}
    {can('analyst')&&filtered.filter(record=>record.status==='processing_failed').map(record=><button key={`retry-${record.record_id}`} className="button button-secondary" disabled={decision.isPending} onClick={()=>decide(record,'approved')}>{t('retry')}</button>)}
    {more.isError&&<div className="state-panel" role="status"><strong>{t('staleDataWarning')}</strong><button className="button button-secondary" onClick={loadMore}>{t('retry')}</button></div>}
    {pageMeta.offset<pageMeta.total&&<button className="button button-secondary" disabled={more.isPending} onClick={loadMore}>{more.isPending?t('loading'):t('loadMore')}</button>}
    {Boolean(pageMeta.malformed)&&can('analyst')&&<details className="state-panel"><summary>{t('technicalDetails')}</summary><p>{t('malformedRecordsIgnored',{count:number(pageMeta.malformed)})}</p></details>}
  </section>;
}
