import { act, cleanup, render, screen, waitFor } from '@testing-library/react';
import userEvent from '@testing-library/user-event';
import { afterEach, beforeEach, describe, expect, it, vi } from 'vitest';
import type { ExternalJob } from '../api/client';
import { resetExternalImportLifecycleForTests, useExternalImportLifecycle } from '../api/externalImportLifecycle';

const imported = (run='central-run') => new Response(JSON.stringify({run_id:run,status:'completed',imported:0,unchanged:0,updated:0,failed:0,total:0}),{status:200,headers:{'Content-Type':'application/json'}});
const readyJob = (id:string,accepted=0,exportAccepted=accepted):ExternalJob => ({job_id:id,command_id:`cmd-${id}`,state:'completed',created_at:'2026-09-27T10:00:00Z',updated_at:'2026-09-27T10:01:00Z',counts:{accepted_records:accepted},sources:{},export:{status:'completed',run_id:`ext-${id}`,dataset_sha256:'a'.repeat(64),accepted_records:exportAccepted,review_records:0}});
function deferred<T>() { let resolve!:(value:T)=>void;let reject!:(error:unknown)=>void;const promise=new Promise<T>((yes,no)=>{resolve=yes;reject=no});return {promise,resolve,reject}; }
function Harness({job,tick=0}:{job?:ExternalJob;tick?:number}) { const lifecycle=useExternalImportLifecycle(job,()=>undefined);return <div data-tick={tick}><span>{lifecycle.state.stage}</span><code>{lifecycle.state.code}</code>{lifecycle.state.stage==='import_failed'&&<button onClick={lifecycle.retry}>Retry Import</button>}</div>; }

beforeEach(()=>{sessionStorage.setItem('cti_access_token','token');resetExternalImportLifecycleForTests();});
afterEach(()=>{cleanup();resetExternalImportLifecycleForTests();sessionStorage.clear();vi.restoreAllMocks();});

describe('production DOM external import lifecycle',()=>{
  it.each([[0,0],[15,30]])('starts one real POST for a terminal export with accepted=%s export.accepted=%s',async(accepted,exportAccepted)=>{const fetchMock=vi.spyOn(globalThis,'fetch').mockResolvedValue(imported());render(<Harness job={readyJob(`job-count-${accepted}-${exportAccepted}`,accepted,exportAccepted)}/>);await screen.findByText('import_succeeded');expect(fetchMock.mock.calls.filter(([input,init])=>String(input).endsWith('/jobs/import')&&init?.method==='POST')).toHaveLength(1)});

  it('does not abort or duplicate the deferred POST during rerender',async()=>{const pending=deferred<Response>();let signal:AbortSignal|undefined;const fetchMock=vi.spyOn(globalThis,'fetch').mockImplementation((_input,init)=>{signal=init?.signal as AbortSignal;return pending.promise});const job=readyJob('job-rerender-123456');const view=render(<Harness job={job}/>);await screen.findByText('import_request_started');view.rerender(<Harness job={{...job}} tick={1}/>);expect(signal?.aborted).toBe(false);expect(fetchMock).toHaveBeenCalledTimes(1);await act(async()=>pending.resolve(imported()));await screen.findByText('import_succeeded')});

  it('aborts silently on unmount, releases the claim, and retries once on remount',async()=>{const first=deferred<Response>();let firstSignal:AbortSignal|undefined;const fetchMock=vi.spyOn(globalThis,'fetch').mockImplementation((_input,init)=>{if(!firstSignal){firstSignal=init?.signal as AbortSignal;firstSignal.addEventListener('abort',()=>first.reject(new DOMException('Aborted','AbortError')));return first.promise}return Promise.resolve(imported('remounted-run'))});const job=readyJob('job-remount-123456');const view=render(<Harness job={job}/>);await screen.findByText('import_request_started');view.unmount();expect(firstSignal?.aborted).toBe(true);render(<Harness job={job}/>);await screen.findByText('import_succeeded');expect(fetchMock).toHaveBeenCalledTimes(2);expect(screen.queryByRole('alert')).not.toBeInTheDocument()});

  it('releases a failed identity and manual Retry Import starts a second POST',async()=>{let calls=0;const fetchMock=vi.spyOn(globalThis,'fetch').mockImplementation(()=>Promise.resolve(++calls===1?new Response(JSON.stringify({detail:{code:'external_import_failed',message:'safe',retryable:false}}),{status:502,headers:{'Content-Type':'application/json'}}):imported()));render(<Harness job={readyJob('job-failure-123456')}/>);await screen.findByText('import_failed');await userEvent.click(screen.getByRole('button',{name:'Retry Import'}));await screen.findByText('import_succeeded');expect(fetchMock).toHaveBeenCalledTimes(2)});

  it('ignores a stale deferred job after switching to a new import identity',async()=>{const old=deferred<Response>();let oldSignal:AbortSignal|undefined;const fetchMock=vi.spyOn(globalThis,'fetch').mockImplementation((_input,init)=>{const body=JSON.parse(String(init?.body));if(body.job_id==='job-old-123456'){oldSignal=init?.signal as AbortSignal;oldSignal.addEventListener('abort',()=>old.reject(new DOMException('Aborted','AbortError')));return old.promise}return Promise.resolve(imported('new-run'))});const view=render(<Harness job={readyJob('job-old-123456')}/>);await screen.findByText('import_request_started');view.rerender(<Harness job={readyJob('job-new-123456')}/>);await screen.findByText('import_succeeded');expect(oldSignal?.aborted).toBe(true);expect(fetchMock).toHaveBeenCalledTimes(2);await waitFor(()=>expect(screen.getByText('http_parse_succeeded')).toBeInTheDocument())});
});
