import {act,cleanup,render,screen,waitFor} from '@testing-library/react';
import userEvent from '@testing-library/user-event';
import {afterEach,beforeEach,describe,expect,it,vi} from 'vitest';
import {Link,MemoryRouter,Route,Routes,useLocation} from 'react-router-dom';
import type {ExternalIngestionOperation,ExternalJob} from '../api/client';
import {EXTERNAL_IMPORT_MONITORING_MAX_MS,resetExternalImportLifecycleForTests,useExternalImportLifecycle} from '../api/externalImportLifecycle';
const readyJob=(id:string,accepted=0,exportAccepted=accepted):ExternalJob=>({job_id:id,command_id:`cmd-${id}`,state:'completed',created_at:'2026-09-27T10:00:00Z',updated_at:'2026-09-27T10:01:00Z',counts:{accepted_records:accepted},sources:{},export:{status:'completed',run_id:`ext-${id}`,dataset_sha256:'a'.repeat(64),accepted_records:exportAccepted,review_records:0}});
const operation=(job:string,state='queued',id=`op-${job}`):ExternalIngestionOperation=>({operation_id:id,operation_type:'external_ingestion',state,stage:state==='completed'?'completed':'central_importing',retryable:state!=='completed',attempt_count:1,external_job_id:job,export_run_id:`ext-${job}`,dataset_sha256:'a'.repeat(64),collected:15,exported:15,imported:state==='completed'?15:0,created:state==='completed'?15:0,updated:0,unchanged:0,failed:0,acknowledged:state==='completed'?15:0,created_at:'2026-09-27T10:00:00Z',updated_at:'2026-09-27T10:01:00Z',completed_at:state==='completed'?'2026-09-27T10:01:00Z':undefined,pipeline_run_id:state==='completed'?'central-run':undefined});
const json=(value:unknown,status=200)=>new Response(JSON.stringify(value),{status,headers:{'Content-Type':'application/json'}});
function deferred<T>(){let resolve!:(v:T)=>void,reject!:(e:unknown)=>void;const promise=new Promise<T>((yes,no)=>{resolve=yes;reject=no});return{promise,resolve,reject}}
function Harness({job,tick=0}:{job?:ExternalJob;tick?:number}){const lifecycle=useExternalImportLifecycle(job,()=>undefined);return <div data-tick={tick}><span>{lifecycle.state.stage}</span><code>{lifecycle.state.code}</code>{lifecycle.state.stage==='import_failed'&&<button onClick={lifecycle.retry}>Retry Import</button>}{lifecycle.state.stage==='monitoring_paused'&&<button onClick={lifecycle.resume}>Resume Monitoring</button>}</div>}
function Location(){return <output>{useLocation().pathname}</output>}
beforeEach(()=>{vi.useFakeTimers({shouldAdvanceTime:true});sessionStorage.setItem('cti_access_token','token');resetExternalImportLifecycleForTests()});
afterEach(()=>{cleanup();resetExternalImportLifecycleForTests();sessionStorage.clear();vi.useRealTimers();vi.restoreAllMocks()});
describe('durable external ingestion DOM lifecycle',()=>{
 it.each([[0,0],[15,30]])('creates one operation for terminal accepted=%s export=%s',async(accepted,exportAccepted)=>{let gets=0;const fetchMock=vi.spyOn(globalThis,'fetch').mockImplementation((_input,init)=>{if(init?.method==='POST')return Promise.resolve(json(operation(`job-count-${accepted}-${exportAccepted}`)));gets++;return Promise.resolve(json(operation(`job-count-${accepted}-${exportAccepted}`,gets?'completed':'queued')))});render(<Harness job={readyJob(`job-count-${accepted}-${exportAccepted}`,accepted,exportAccepted)}/>);await screen.findByText('import_succeeded');expect(fetchMock.mock.calls.filter(([input,init])=>String(input).endsWith('/external-ingestions')&&init?.method==='POST')).toHaveLength(1)});
 it('rerender does not cancel or duplicate deferred operation creation',async()=>{const pending=deferred<Response>();let signal:AbortSignal|undefined;const fetchMock=vi.spyOn(globalThis,'fetch').mockImplementation((input,init)=>{if(String(input).endsWith('/external-ingestions')){signal=init?.signal as AbortSignal;return pending.promise}return Promise.resolve(json(operation('job-rerender-123456','completed')))});const job=readyJob('job-rerender-123456'),view=render(<Harness job={job}/>);await screen.findByText('import_ready');view.rerender(<Harness job={{...job}} tick={1}/>);expect(signal?.aborted).toBe(false);expect(fetchMock).toHaveBeenCalledTimes(1);await act(async()=>pending.resolve(json(operation(job.job_id))));await screen.findByText('import_succeeded')});
 it('unmount is silent and remount observes the same durable operation',async()=>{const pending=deferred<Response>();let signal:AbortSignal|undefined;let posts=0;vi.spyOn(globalThis,'fetch').mockImplementation((input,init)=>{if(String(input).endsWith('/external-ingestions')){posts++;signal=init?.signal as AbortSignal;return pending.promise}return Promise.resolve(json(operation('job-remount-123456','completed')))});const job=readyJob('job-remount-123456'),view=render(<Harness job={job}/>);await screen.findByText('import_ready');view.unmount();expect(signal?.aborted).toBe(true);sessionStorage.setItem('cti_external_ingestion_operations_v1',JSON.stringify({[`${job.job_id}:${job.export!.run_id}:${job.export!.dataset_sha256}`]:'op-job-remount-123456'}));render(<Harness job={job}/>);await screen.findByText('import_succeeded');expect(posts).toBe(1)});
 it('manual retry resumes the same operation',async()=>{let retry=0;vi.spyOn(globalThis,'fetch').mockImplementation((input)=>{const path=String(input);if(path.endsWith('/external-ingestions'))return Promise.resolve(json(operation('job-failure-123456')));if(path.endsWith('/retry')){retry++;return Promise.resolve(json(operation('job-failure-123456','completed')))}if(retry)return Promise.resolve(json(operation('job-failure-123456','completed')));return Promise.resolve(json({...operation('job-failure-123456','failed_retryable'),error:{code:'upstream_unavailable',stage:'central_importing',retryable:true,message:'safe'}}))});render(<Harness job={readyJob('job-failure-123456')}/>);await screen.findByText('import_failed');await userEvent.click(screen.getByRole('button',{name:'Retry Import'}));await screen.findByText('import_succeeded');expect(retry).toBe(1)});
 it('stale operation cannot replace a newer job',async()=>{const old=deferred<Response>();vi.spyOn(globalThis,'fetch').mockImplementation((input,init)=>{const path=String(input);if(path.endsWith('/external-ingestions')&&String(init?.body).includes('job-old'))return old.promise;if(path.endsWith('/external-ingestions'))return Promise.resolve(json(operation('job-new-123456')));return Promise.resolve(json(operation('job-new-123456','completed')))});const view=render(<Harness job={readyJob('job-old-123456')}/>);await screen.findByText('import_ready');view.rerender(<Harness job={readyJob('job-new-123456')}/>);await screen.findByText('import_succeeded');await act(async()=>old.resolve(json(operation('job-old-123456','completed'))));await waitFor(()=>expect(screen.getByText('central_commit_proven')).toBeInTheDocument())});
 it.each([['Dashboard','/dashboard'],['Accepted Records','/accepted-records'],['Processing Center','/processing-center']])('active polling unmounts immediately when navigating to %s',async(label,path)=>{const pending=deferred<Response>();let signal:AbortSignal|undefined;vi.spyOn(globalThis,'fetch').mockImplementation((_input,init)=>{signal=init?.signal as AbortSignal;return pending.promise});render(<MemoryRouter initialEntries={['/external-sources']}><Location/><Routes><Route path="/external-sources" element={<><Harness job={readyJob('job-navigation-123456')}/><Link to={path}>{label}</Link></>}/><Route path={path} element={<h1>{label}</h1>}/></Routes></MemoryRouter>);await screen.findByText('import_ready');await userEvent.click(screen.getByRole('link',{name:label}));expect(screen.getByRole('heading',{name:label})).toBeInTheDocument();expect(screen.getByText(path)).toBeInTheDocument();expect(signal?.aborted).toBe(true)});
 it('pauses only browser monitoring and resumes the exact durable operation',async()=>{let statusCalls=0,recover=false;vi.spyOn(globalThis,'fetch').mockImplementation((_input,init)=>{if(init?.method==='POST')return Promise.resolve(json(operation('job-pause-123456')));statusCalls++;return Promise.resolve(json(operation('job-pause-123456',recover?'completed':'central_importing')))});render(<Harness job={readyJob('job-pause-123456')}/>);await screen.findByText('import_request_started');await act(async()=>{await vi.advanceTimersByTimeAsync(EXTERNAL_IMPORT_MONITORING_MAX_MS)});await screen.findByText('monitoring_paused');recover=true;await userEvent.click(screen.getByRole('button',{name:'Resume Monitoring'}));await screen.findByText('import_succeeded');expect(statusCalls).toBeGreaterThan(0)});
});
