import { cleanup, render, screen, waitFor } from '@testing-library/react';
import userEvent from '@testing-library/user-event';
import { afterEach, describe, expect, it, vi } from 'vitest';
import { ar, en, I18nProvider } from '../i18n/I18nContext';
import { LanguageToggle } from '../components/LanguageToggle';
import { Layout } from '../components/Layout';
import { renderWithProviders } from './fixtures';
import { ProcessingCenter } from '../pages/ProcessingCenter';

const json=(value:unknown,status=200)=>Promise.resolve(new Response(JSON.stringify(value),{status,headers:{'Content-Type':'application/json'}}));
const user={id:'u',username:'analyst',role:'analyst',is_active:true};
const source={source_id:'source-one',name:'Safe source',source_type:'rss',status:'enabled',metadata:{}};
const watch={watch_id:'watch-1234567890',keyword:'Acme',enabled:true,created_at:'2026-09-01T00:00:00Z',updated_at:'2026-09-01T00:00:00Z',result_count:0,new_result_count:0};
const job={schema_version:'1.0',job_id:'job-center-1234',command_id:'cmd-center-1234',state:'completed',created_at:'2026-09-01T00:00:00Z',updated_at:'2026-09-01T00:00:01Z',progress:{},result:{accepted_records:1},error:null};
const preview={schema_version:'1.0',preview_id:'preview-center-1234567890',state:'pending',created_at:'2026-09-01T00:00:00Z',expires_at:'2099-09-01T00:00:00Z',display_url:'https://example.org/report',page_type:'article',title:'Safe preview',excerpt:'Sanitized excerpt',disposition:'accepted',privacy_status:'reviewed',review_reasons:[],content_sha256:'sha256:'+''.padEnd(64,'a'),items_preview:[],items_preview_total:0,items_preview_truncated:false,counts:{items:0,accepted:0,review:0,rejected:0,skipped:0,errors:0}};
function centerMock(handler?:(path:string,init?:RequestInit)=>Promise<Response>){sessionStorage.setItem('cti_access_token','token');return vi.spyOn(globalThis,'fetch').mockImplementation((input,init)=>{const p=String(input);if(p.endsWith('/auth/me'))return json(user);if(p.endsWith('/integrations/external-control/sources'))return json([source]);if(p.endsWith('/dark-web/watches'))return json({schema_version:'1.0',items:[watch]});if(p.includes('/dashboard/summary'))return json({events:0,indicators:0,observables:0,correlations:0,sessions:0,outliers:0,by_severity:{},by_pipeline:{}});if(p.includes('indicators-summary'))return json({total:0,by_role:{},by_assessment:{},by_validation:{},by_type:{}});if(p.includes('/intelligence/'))return json({items:[],total:0,limit:5,offset:0});return handler?handler(p,init):json(job)})}
afterEach(()=>{cleanup();sessionStorage.clear();vi.restoreAllMocks()});
describe('local i18n and orchestration navigation',()=>{
  it('keeps Arabic and English translation keys identical',()=>expect(Object.keys(en).sort()).toEqual(Object.keys(ar).sort()));
  it('switches lang and direction and safely defaults corrupt storage to Arabic',async()=>{sessionStorage.setItem('cti_language','corrupt');render(<I18nProvider><LanguageToggle/></I18nProvider>);expect(document.documentElement).toHaveAttribute('dir','rtl');await userEvent.setup().click(screen.getByRole('button',{name:'Switch to English'}));expect(document.documentElement).toHaveAttribute('lang','en');expect(document.documentElement).toHaveAttribute('dir','ltr');expect(sessionStorage.getItem('cti_language')).toBe('en')});
  it('exposes the processing center and collapsible accessible navigation',async()=>{sessionStorage.setItem('cti_access_token','token');vi.spyOn(globalThis,'fetch').mockImplementation(input=>String(input).endsWith('/auth/me')?json({id:'u',username:'analyst',role:'analyst',is_active:true}):json({}));renderWithProviders(<Layout/>,['/processing-center']);await waitFor(()=>expect(screen.getByText('analyst')).toBeInTheDocument());expect(screen.getByRole('link',{name:'مركز المعالجة والتحليل'})).toHaveClass('active');const collapse=screen.getByRole('button',{name:'طي القائمة'});await userEvent.setup().click(collapse);expect(collapse).toHaveAttribute('aria-expanded','false')});
  it('keeps viewers read-only in the processing center',async()=>{sessionStorage.setItem('cti_access_token','token');vi.spyOn(globalThis,'fetch').mockImplementation(input=>{const p=String(input);if(p.endsWith('/auth/me'))return json({id:'u',username:'viewer',role:'viewer',is_active:true});if(p.endsWith('/sources'))return json([]);if(p.endsWith('/dark-web/watches'))return json({schema_version:'1.0',items:[]});if(p.includes('/dashboard/summary'))return json({events:0,indicators:0,observables:0,correlations:0,sessions:0,outliers:0,by_severity:{},by_pipeline:{}});if(p.includes('indicators-summary'))return json({total:0,by_role:{},by_assessment:{},by_validation:{},by_type:{}});return json({items:[],total:0,limit:p.includes('limit=5')?5:1,offset:0})});renderWithProviders(<ProcessingCenter/>);expect(await screen.findByText('حساب المشاهد للقراءة فقط.')).toBeInTheDocument();expect(screen.queryByRole('button',{name:'بدء المعالجة'})).not.toBeInTheDocument()});
  it.each([
    ['external','source-one','/sources/source-one/jobs'],
    ['dark','watch-1234567890','/dark-web/watches/watch-1234567890/scan'],
    ['internal','dionaea','/integrations/dionaea/pull'],
    ['internal','host-auth','/integrations/host-auth/pull'],
    ['internal','web-access','/integrations/web-access/pull'],
  ])('confirms and submits one %s input for %s',async(kind,selection,path)=>{const fetchMock=centerMock((request)=>request.endsWith('/pull')?json({run_id:'run-center-1',pipeline:'internal',status:'completed',collected_count:1,processed_count:1,stored_count:1,failed_count:0}):json(job));vi.spyOn(window,'confirm').mockReturnValue(true);renderWithProviders(<ProcessingCenter/>);const actor=userEvent.setup();await screen.findByText('Safe source');await actor.selectOptions(screen.getByLabelText('نوع المدخل'),kind);await actor.selectOptions(screen.getByLabelText('اختر'),selection);const button=screen.getByRole('button',{name:'بدء المعالجة'});await actor.click(button);expect(fetchMock.mock.calls.filter(([input])=>String(input).endsWith(path))).toHaveLength(1);expect(window.confirm).toHaveBeenCalled();expect(await screen.findByText(kind==='internal'?'run-center-1':'job-center-1234')).toBeInTheDocument()});
  it('previews a manual URL and requires confirmation for approve and reject',async()=>{const fetchMock=centerMock((path)=>path.endsWith('/previews')?json(preview,201):path.endsWith('/approve')?json(job):json({schema_version:'1.0',preview_id:preview.preview_id,state:'rejected',decided_at:'2026-09-01T00:01:00Z'}));vi.spyOn(window,'confirm').mockReturnValue(true);renderWithProviders(<ProcessingCenter/>);const actor=userEvent.setup();await screen.findByText('Safe source');await actor.selectOptions(screen.getByLabelText('نوع المدخل'),'manual');await actor.type(screen.getByLabelText('رابط HTTP أو HTTPS'),'https://example.org/report');await actor.click(screen.getByRole('button',{name:'بدء المعالجة'}));expect(await screen.findByText('Safe preview')).toBeInTheDocument();await actor.click(screen.getByRole('button',{name:'اعتماد وحفظ'}));expect(fetchMock.mock.calls.some(([input])=>String(input).endsWith('/approve'))).toBe(true);expect(await screen.findByText('job-center-1234')).toBeInTheDocument()});
  it('shows a translated unconfigured watch state',async()=>{centerMock();renderWithProviders(<ProcessingCenter/>);const actor=userEvent.setup();await screen.findByText('Safe source');await actor.selectOptions(screen.getByLabelText('نوع المدخل'),'dark');expect(screen.getByText('اختر')).toBeInTheDocument();cleanup();sessionStorage.setItem('cti_access_token','token');vi.restoreAllMocks();vi.spyOn(globalThis,'fetch').mockImplementation((input)=>{const p=String(input);if(p.endsWith('/auth/me'))return json(user);if(p.endsWith('/sources'))return json([]);if(p.endsWith('/dark-web/watches'))return json({schema_version:'1.0',items:[]});if(p.includes('/dashboard/summary'))return json({events:0,indicators:0,observables:0,correlations:0,sessions:0,outliers:0,by_severity:{},by_pipeline:{}});if(p.includes('indicators-summary'))return json({total:0,by_role:{},by_assessment:{},by_validation:{},by_type:{}});return json({items:[],total:0,limit:5,offset:0})});renderWithProviders(<ProcessingCenter/>);await actor.selectOptions(await screen.findByLabelText('نوع المدخل'),'dark');expect(screen.getByText('لا توجد مراقبات Dark Web مفعّلة.')).toBeInTheDocument()});
});
