import { act, cleanup, render, screen, waitFor } from '@testing-library/react';
import userEvent from '@testing-library/user-event';
import { afterEach, describe, expect, it, vi } from 'vitest';
import { ar, en, I18nProvider } from '../i18n/I18nContext';
import { LanguageToggle } from '../components/LanguageToggle';
import { Layout } from '../components/Layout';
import { renderWithProviders } from './fixtures';
import { PROCESSING_CENTER_JOB_POLL_MAX_MS, ProcessingCenter } from '../pages/ProcessingCenter';

const json=(value:unknown,status=200)=>Promise.resolve(new Response(JSON.stringify(value),{status,headers:{'Content-Type':'application/json'}}));
const user={id:'u',username:'analyst',role:'analyst',is_active:true};
const source={source_id:'source-one',name:'Safe source',source_type:'rss',status:'enabled',metadata:{}};
const watch={watch_id:'watch-1234567890',keyword:'Acme',provider_id:'ready-provider',enabled:true,created_at:'2026-09-01T00:00:00Z',updated_at:'2026-09-01T00:00:00Z',result_count:0,new_result_count:0};
const job={schema_version:'1.0',job_id:'job-center-1234',command_id:'cmd-center-1234',state:'completed',created_at:'2026-09-01T00:00:00Z',updated_at:'2026-09-01T00:00:01Z',progress:{},result:{accepted_records:1},error:null};
const externalJob=(jobId:string,state='queued')=>({...job,job_id:jobId,command_id:`cmd-${jobId.slice(4)}`,state,result:state==='completed'?{accepted_records:1}:null});
const preview={schema_version:'1.0',preview_id:'preview-center-1234567890',state:'pending',created_at:'2026-09-01T00:00:00Z',expires_at:'2099-09-01T00:00:00Z',display_url:'https://example.org/report',page_type:'article',title:'Safe preview',excerpt:'Sanitized excerpt',disposition:'accepted',privacy_status:'reviewed',review_reasons:[],content_sha256:'sha256:'+''.padEnd(64,'a'),items_preview:[],items_preview_total:0,items_preview_truncated:false,counts:{items:0,accepted:0,review:0,rejected:0,skipped:0,errors:0}};
function centerMock(handler?:(path:string,init?:RequestInit)=>Promise<Response>,availableSources=[source]){sessionStorage.setItem('cti_access_token','token');return vi.spyOn(globalThis,'fetch').mockImplementation((input,init)=>{const p=String(input);if(p.endsWith('/auth/me'))return json(user);if(p.endsWith('/integrations/external-control/sources'))return json(availableSources);if(p.endsWith('/dark-web/watches'))return json({schema_version:'1.0',items:[watch]});if(p.endsWith('/dark-web/discovery/providers'))return json([{provider_id:'ready-provider',enabled:true,ready:true,through_tor:true}]);if(p.includes('/dashboard/summary'))return json({events:0,indicators:0,observables:0,correlations:0,sessions:0,outliers:0,by_severity:{},by_pipeline:{}});if(p.includes('indicators-summary'))return json({total:0,by_role:{},by_assessment:{},by_validation:{},by_type:{}});if(p.includes('/intelligence/'))return json({items:[],total:0,limit:5,offset:0});return handler?handler(p,init):json(job)})}
afterEach(()=>{cleanup();sessionStorage.clear();vi.restoreAllMocks()});
describe('local i18n and orchestration navigation',()=>{
  it('keeps Arabic and English translation keys identical',()=>expect(Object.keys(en).sort()).toEqual(Object.keys(ar).sort()));
  it('switches lang and direction and shows the destination-language symbol',async()=>{sessionStorage.setItem('cti_language','corrupt');render(<I18nProvider><LanguageToggle/></I18nProvider>);const toggle=screen.getByRole('button',{name:'Switch to English'});expect(toggle).toHaveTextContent('E');expect(toggle).toHaveAttribute('title','Switch to English');expect(document.documentElement).toHaveAttribute('dir','rtl');await userEvent.setup().click(toggle);const arabicToggle=screen.getByRole('button',{name:'التبديل إلى العربية'});expect(arabicToggle).toHaveTextContent('ع');expect(arabicToggle).toHaveAttribute('title','التبديل إلى العربية');expect(document.documentElement).toHaveAttribute('lang','en');expect(document.documentElement).toHaveAttribute('dir','ltr');expect(sessionStorage.getItem('cti_language')).toBe('en')});
  it('exposes the processing center and collapsible accessible navigation',async()=>{sessionStorage.setItem('cti_access_token','token');vi.spyOn(globalThis,'fetch').mockImplementation(input=>String(input).endsWith('/auth/me')?json({id:'u',username:'analyst',role:'analyst',is_active:true}):json({}));renderWithProviders(<Layout/>,['/processing-center']);await waitFor(()=>expect(screen.getByText('analyst')).toBeInTheDocument());expect(screen.getByRole('link',{name:'مركز المعالجة والتحليل'})).toHaveClass('active');const collapse=screen.getByRole('button',{name:'طي القائمة'});await userEvent.setup().click(collapse);expect(collapse).toHaveAttribute('aria-expanded','false')});
  it('keeps viewers read-only in the processing center',async()=>{sessionStorage.setItem('cti_access_token','token');vi.spyOn(globalThis,'fetch').mockImplementation(input=>{const p=String(input);if(p.endsWith('/auth/me'))return json({id:'u',username:'viewer',role:'viewer',is_active:true});if(p.endsWith('/sources'))return json([]);if(p.endsWith('/dark-web/watches'))return json({schema_version:'1.0',items:[]});if(p.includes('/dashboard/summary'))return json({events:0,indicators:0,observables:0,correlations:0,sessions:0,outliers:0,by_severity:{},by_pipeline:{}});if(p.includes('indicators-summary'))return json({total:0,by_role:{},by_assessment:{},by_validation:{},by_type:{}});return json({items:[],total:0,limit:p.includes('limit=5')?5:1,offset:0})});renderWithProviders(<ProcessingCenter/>);expect(await screen.findByText('حساب المشاهد للقراءة فقط.')).toBeInTheDocument();expect(screen.queryByRole('button',{name:'بدء المعالجة'})).not.toBeInTheDocument()});
  it.each([
    ['external','source-one','/sources/source-one/jobs'],
    ['dark','watch-1234567890','/dark-web/watches/watch-1234567890/scan'],
    ['internal','dionaea','/integrations/dionaea/pull'],
    ['internal','host-auth','/integrations/host-auth/pull'],
    ['internal','web-access','/integrations/web-access/pull'],
  ])('confirms and submits one %s input for %s',async(kind,selection,path)=>{const fetchMock=centerMock((request)=>request.endsWith('/pull')?json({run_id:'run-center-1',pipeline:'internal',status:'completed',collected_count:1,processed_count:1,stored_count:1,failed_count:0}):json(job));vi.spyOn(window,'confirm').mockReturnValue(true);renderWithProviders(<ProcessingCenter/>);const actor=userEvent.setup();await screen.findByText('Safe source');await actor.selectOptions(screen.getByLabelText('نوع المدخل'),kind);await actor.selectOptions(screen.getByLabelText('اختر'),selection);const button=screen.getByRole('button',{name:'بدء المعالجة'});await actor.click(button);expect(fetchMock.mock.calls.filter(([input])=>String(input).endsWith(path))).toHaveLength(1);expect(window.confirm).toHaveBeenCalled();expect(await screen.findByText(kind==='internal'?'run-center-1':'job-center-1234')).toBeInTheDocument()});
  it('previews a manual URL and requires confirmation for approve and reject',async()=>{const fetchMock=centerMock((path)=>path.endsWith('/previews')?json(preview,201):path.endsWith('/approve')?json(job):json({schema_version:'1.0',preview_id:preview.preview_id,state:'rejected',decided_at:'2026-09-01T00:01:00Z'}));vi.spyOn(window,'confirm').mockReturnValue(true);renderWithProviders(<ProcessingCenter/>);const actor=userEvent.setup();await screen.findByText('Safe source');await actor.selectOptions(screen.getByLabelText('نوع المدخل'),'manual');await actor.type(screen.getByLabelText('رابط HTTP أو HTTPS'),'https://example.org/report');await actor.click(screen.getByRole('button',{name:'بدء المعالجة'}));expect(await screen.findByText('Safe preview')).toBeInTheDocument();await actor.click(screen.getByRole('button',{name:'اعتماد وحفظ'}));expect(fetchMock.mock.calls.some(([input])=>String(input).endsWith('/approve'))).toBe(true);expect(await screen.findByText('job-center-1234')).toBeInTheDocument()});
  it('shows a translated unconfigured watch state',async()=>{centerMock();renderWithProviders(<ProcessingCenter/>);const actor=userEvent.setup();await screen.findByText('Safe source');await actor.selectOptions(screen.getByLabelText('نوع المدخل'),'dark');expect(screen.getByText('اختر')).toBeInTheDocument();cleanup();sessionStorage.setItem('cti_access_token','token');vi.restoreAllMocks();vi.spyOn(globalThis,'fetch').mockImplementation((input)=>{const p=String(input);if(p.endsWith('/auth/me'))return json(user);if(p.endsWith('/sources'))return json([]);if(p.endsWith('/dark-web/watches'))return json({schema_version:'1.0',items:[]});if(p.includes('/dashboard/summary'))return json({events:0,indicators:0,observables:0,correlations:0,sessions:0,outliers:0,by_severity:{},by_pipeline:{}});if(p.includes('indicators-summary'))return json({total:0,by_role:{},by_assessment:{},by_validation:{},by_type:{}});return json({items:[],total:0,limit:5,offset:0})});renderWithProviders(<ProcessingCenter/>);await actor.selectOptions(await screen.findByLabelText('نوع المدخل'),'dark');expect(screen.getByText('لا توجد مراقبات Dark Web مفعّلة.')).toBeInTheDocument()});
});

describe('processing center job identity and polling isolation',()=>{
  it('prevents duplicate Processing Center submissions',async()=>{let resolvePost!:(value:Response)=>void;const pending=new Promise<Response>(resolve=>{resolvePost=resolve});const fetchMock=centerMock((_path,init)=>init?.method==='POST'?pending:json(externalJob('job-duplicate-123456789')));vi.spyOn(window,'confirm').mockReturnValue(true);renderWithProviders(<ProcessingCenter/>);await screen.findByText('Safe source');const actor=userEvent.setup();await actor.selectOptions(screen.getByLabelText('اختر'),'source-one');const button=screen.getByRole('button',{name:'بدء المعالجة'});await actor.click(button);expect(button).toBeDisabled();await actor.click(button);expect(fetchMock.mock.calls.filter(([,init])=>init?.method==='POST')).toHaveLength(1);resolvePost(await json(externalJob('job-duplicate-123456789','completed')));await screen.findByText('job-duplicate-123456789')});
  it('displays and polls exactly the job ID returned by POST and stops when terminal',async()=>{const returned=externalJob('job-0a33ffd457199c868d7b8a30');const completed=externalJob(returned.job_id,'completed');const fetchMock=centerMock((_path,init)=>init?.method==='POST'?json(returned):json(completed));vi.spyOn(window,'confirm').mockReturnValue(true);renderWithProviders(<ProcessingCenter/>);await screen.findByText('Safe source');await userEvent.setup().selectOptions(screen.getByLabelText('اختر'),'source-one');await userEvent.setup().click(screen.getByRole('button',{name:'بدء المعالجة'}));expect(await screen.findByText(returned.job_id)).toBeInTheDocument();await waitFor(()=>expect(fetchMock.mock.calls.some(([input,init])=>!init?.method&&String(input).endsWith(`/integrations/external-control/jobs/${returned.job_id}`))).toBe(true));await screen.findByLabelText('الحالة: مكتملة');const polls=fetchMock.mock.calls.filter(([input])=>String(input).includes(`/jobs/${returned.job_id}`)).length;await new Promise(resolve=>window.setTimeout(resolve,20));expect(fetchMock.mock.calls.filter(([input])=>String(input).includes(`/jobs/${returned.job_id}`))).toHaveLength(polls);expect(document.body).not.toHaveTextContent('job-47c96783ee45492d25f29669')});

  it('aborts old polling and ignores its late response when another input starts',async()=>{const second={...source,source_id:'source-two',name:'Second source'};let resolveOld!:(value:Response)=>void;const oldPoll=new Promise<Response>(resolve=>{resolveOld=resolve});let oldSignal:AbortSignal|undefined;const fetchMock=centerMock((path,init)=>{if(init?.method==='POST'&&path.includes('source-one'))return json(externalJob('job-first-1234567890'));if(init?.method==='POST'&&path.includes('source-two'))return json(externalJob('job-second-123456789'));if(path.endsWith('/jobs/job-first-1234567890')){oldSignal=init?.signal as AbortSignal;return oldPoll}return json(externalJob('job-second-123456789','completed'))},[source,second]);vi.spyOn(window,'confirm').mockReturnValue(true);renderWithProviders(<ProcessingCenter/>);const actor=userEvent.setup();await screen.findByText('Second source');await actor.selectOptions(screen.getByLabelText('اختر'),'source-one');await actor.click(screen.getByRole('button',{name:'بدء المعالجة'}));await screen.findByText('job-first-1234567890');await waitFor(()=>expect(oldSignal).toBeDefined());await actor.selectOptions(screen.getByLabelText('اختر'),'source-two');await actor.click(screen.getByRole('button',{name:'بدء المعالجة'}));expect(await screen.findByText('job-second-123456789')).toBeInTheDocument();await waitFor(()=>expect(oldSignal?.aborted).toBe(true));resolveOld(await json(externalJob('job-first-1234567890','completed')));await act(async()=>{await Promise.resolve()});expect(screen.getByText('job-second-123456789')).toBeInTheDocument();expect(screen.queryByText('job-first-1234567890')).not.toBeInTheDocument();expect(fetchMock.mock.calls.filter(([input,init])=>init?.method==='POST'&&String(input).includes('/sources/'))).toHaveLength(2)});

  it('automatically recovers one transient 503 without another POST or exposing detail',async()=>{vi.useFakeTimers({shouldAdvanceTime:true});const current=externalJob('job-retry-1234567890');let polls=0;const fetchMock=centerMock((path,init)=>{if(init?.method==='POST')return json(current);if(path.endsWith(`/jobs/${current.job_id}`)){polls+=1;return polls===1?json({detail:'External Sources control API is unreachable at http://10.0.0.1 token=secret'},503):json(externalJob(current.job_id,'completed'))}return json(current)});vi.spyOn(window,'confirm').mockReturnValue(true);renderWithProviders(<ProcessingCenter/>);await screen.findByText('Safe source');const actor=userEvent.setup({advanceTimers:vi.advanceTimersByTime});await actor.selectOptions(screen.getByLabelText('اختر'),'source-one');await actor.click(screen.getByRole('button',{name:'بدء المعالجة'}));expect(await screen.findByRole('status')).toHaveTextContent('جار إعادة الاتصال');expect(screen.getByText(current.job_id)).toBeInTheDocument();expect(document.body).not.toHaveTextContent('10.0.0.1');expect(document.body).not.toHaveTextContent('token=secret');await act(async()=>{await vi.advanceTimersByTimeAsync(2_000)});await screen.findByLabelText('الحالة: مكتملة');expect(fetchMock.mock.calls.filter(([,init])=>init?.method==='POST')).toHaveLength(1);expect(fetchMock.mock.calls.filter(([input])=>String(input).endsWith(`/jobs/${current.job_id}`))).toHaveLength(2)});

  it('distinguishes bounded polling timeout from External Control unavailability',async()=>{vi.useFakeTimers({shouldAdvanceTime:true});const current=externalJob('job-timeout-123456789');centerMock((_path,init)=>init?.method==='POST'?json(current):new Promise<Response>(()=>undefined));vi.spyOn(window,'confirm').mockReturnValue(true);renderWithProviders(<ProcessingCenter/>);await screen.findByText('Safe source');const actor=userEvent.setup({advanceTimers:vi.advanceTimersByTime});await actor.selectOptions(screen.getByLabelText('اختر'),'source-one');await actor.click(screen.getByRole('button',{name:'بدء المعالجة'}));await screen.findByText(current.job_id);await act(async()=>{vi.advanceTimersByTime(PROCESSING_CENTER_JOB_POLL_MAX_MS);await Promise.resolve()});expect(screen.getByRole('alert')).toHaveTextContent('انتهت مهلة متابعة الوظيفة');expect(screen.getByRole('alert')).not.toHaveTextContent('خدمة التحكم بالمصادر الخارجية غير متاحة حاليًا')});

  it('pauses after the transient threshold and manual retry polls the same job',async()=>{
    vi.useFakeTimers({shouldAdvanceTime:true});const current=externalJob('job-threshold-123456789');let recover=false;
    const fetchMock=centerMock((_path,init)=>init?.method==='POST'?json(current):recover?json(externalJob(current.job_id,'completed')):json({detail:'private token=secret'},503));
    vi.spyOn(window,'confirm').mockReturnValue(true);renderWithProviders(<ProcessingCenter/>);await screen.findByText('Safe source');const actor=userEvent.setup({advanceTimers:vi.advanceTimersByTime});await actor.selectOptions(screen.getByLabelText('اختر'),'source-one');await actor.click(screen.getByRole('button',{name:'بدء المعالجة'}));
    for(const delay of [2_000,4_000,8_000,10_000]) await act(async()=>{await vi.advanceTimersByTimeAsync(delay)});
    expect(await screen.findByRole('alert')).toHaveTextContent('خدمة التحكم بالمصادر الخارجية غير متاحة حاليًا');expect(screen.getByText(current.job_id)).toBeInTheDocument();expect(document.body).not.toHaveTextContent('token=secret');
    recover=true;await actor.click(screen.getByRole('button',{name:'إعادة المحاولة'}));await screen.findByLabelText('الحالة: مكتملة');expect(fetchMock.mock.calls.filter(([,init])=>init?.method==='POST')).toHaveLength(1);expect(fetchMock.mock.calls.filter(([input])=>String(input).endsWith(`/jobs/${current.job_id}`))).toHaveLength(6);
  });

  it('resets transient backoff after a successful running response',async()=>{
    vi.useFakeTimers({shouldAdvanceTime:true});const current=externalJob('job-reset-1234567890');let poll=0;
    centerMock((_path,init)=>init?.method==='POST'?json(current):[++poll===1, poll===3].some(Boolean)?json({detail:'temporary'},503):json(externalJob(current.job_id,poll===2?'running':'completed')));
    vi.spyOn(window,'confirm').mockReturnValue(true);renderWithProviders(<ProcessingCenter/>);await screen.findByText('Safe source');const actor=userEvent.setup({advanceTimers:vi.advanceTimersByTime});await actor.selectOptions(screen.getByLabelText('اختر'),'source-one');await actor.click(screen.getByRole('button',{name:'بدء المعالجة'}));
    await act(async()=>{await vi.advanceTimersByTimeAsync(2_000)});await screen.findByLabelText('الحالة: قيد التشغيل');await act(async()=>{await vi.advanceTimersByTimeAsync(2_000)});expect(await screen.findByRole('status')).toHaveTextContent('المحاولة 1');await act(async()=>{await vi.advanceTimersByTimeAsync(2_000)});await screen.findByLabelText('الحالة: مكتملة');
  });

  it.each([[401,true,'انتهت جلسة الدخول'],[403,false,'الوصول غير مسموح'],[404,false,'لم تعد الوظيفة موجودة']] as const)('does not automatically retry polling HTTP %s',async(status,clears,message)=>{const current=externalJob(`job-auth-${status}-123456789`);const fetchMock=centerMock((_path,init)=>init?.method==='POST'?json(current):json({detail:'private http://10.0.0.2 token=secret'},status));vi.spyOn(window,'confirm').mockReturnValue(true);renderWithProviders(<ProcessingCenter/>);await screen.findByText('Safe source');const actor=userEvent.setup();await actor.selectOptions(screen.getByLabelText('اختر'),'source-one');await actor.click(screen.getByRole('button',{name:'بدء المعالجة'}));await waitFor(()=>expect(sessionStorage.getItem('cti_access_token')===null).toBe(clears));if(!clears){expect(await screen.findByRole('alert')).toHaveTextContent(message);expect(sessionStorage.getItem('cti_access_token')).toBe('token')}expect(fetchMock.mock.calls.filter(([input])=>String(input).endsWith(`/jobs/${current.job_id}`))).toHaveLength(1);expect(document.body).not.toHaveTextContent('10.0.0.2');expect(document.body).not.toHaveTextContent('token=secret')});
});
