server {
    listen 169.58.249.3:80;
    server_name 169.58.249.3;
    server_tokens off;
    location ^~ /.well-known/acme-challenge/ {
        root /var/www/cti-acme;
        default_type text/plain;
        try_files $uri =404;
    }
    location / { return 404; }
}
